### ISSUE TITLE
Phew qeastions

### ISSUE THREAD

**Issue by LegacyGamerHD** [longjunyu2/MCinaBox#1]
is there a release for it also how does it perform

**Comment by LegacyGamerHD** [comment]
Also what Android persoon does it work

**Comment by LegacyGamerHD** [comment]
I looked add code its chinese its bummer i dont undersrand it plz translate it to english

**Comment by longjunyu2** [comment]
MCinaBox used BoatApp project to launch Minecraft,so it wil work on Android 5.0 and above.
I will add English traslation support in last commit.
And I have to say that MCinaBox can't Launch Minecraft straightly now.It needs some Native Libraries that are same as BoatApp's. 
I am working on control fiction and I will provide full build methods when finished.

**Comment by lizeyan200711** [comment]
Yes, it can't start minecraft now, but mcinabox has a startup factor

**Comment by LegacyGamerHD** [comment]
@longjunyu2  why is the release tab not working  on readme can you release a apk

**Comment by lizeyan200711** [comment]
I suggest you compile one by yourself, because it has many imperfections!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LegacyGamerHD"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 上午9:36
收件人:&nbsp;"longjunyu2/MCinaBox"<MCinaBox@noreply.github.com&gt;;
抄送:&nbsp;"小叶子"<2838632319@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [longjunyu2/MCinaBox] Phew qeastions (#1)





 
@longjunyu2  why is the release tab not working  on readme can you release a apk

**Comment by longjunyu2** [comment]
@LegacyGamerHD MCinaBox is tested on AVD.But Native Libraries can;t be built for X86,so I did't fully tested it for a long time.I will work to rlease a available version,.Need hours :).

**Comment by LegacyGamerHD** [comment]
How do compile dose native libs or how do i add them

**Comment by longjunyu2** [comment]
> How do compile dose native libs or how do i add them

I have to say that this work is difficult for me now. I barely spare time to work on this project.
So it's pity but honest to say that I can't Update the project readme now.
There are too many works to do beside MCinaBox.

**Comment by CPXMC** [comment]
都是外国人吗？

**Comment by yejunjie10311031** [comment]
I have found that the Longjunyu's English speak so fantastic，this make me admire him for his abilities not only he can write MCinabox but also his knowledge,I think he must be a man who has a lot of knowledge.

**Comment by CPXMC** [comment]
> I have found that the Longjunyu's English speak so fantastic，this make me admire him for his abilities not only he can write MCinabox but also his knowledge,I think he must be a man who has a lot of knowledge.

你说的很对，他英语确实很好。
