### ISSUE TITLE
What mods work on here

### ISSUE THREAD

**Issue by blissband123** [longjunyu2/MCinaBox#101]
What are some mods that work

**Comment by gabbosta** [comment]
All, but depending on the cell phone may crash

**Comment by blissband123** [comment]
> All, but depending on the cell phone may crash

I have a galaxy s8 and no mods work on my phone

**Comment by gabbosta** [comment]
Do you have universal forge?

**Comment by blissband123** [comment]
> Do you have universal forge?

Yes i have universal forge for 1.7.10

**Comment by longjunyu2** [comment]
have you installed the forge through ForgeInstaller ins the MCinaBox? if you have done, you just need copy mods to /sdcard/MCinaBox/.minecraft/mods. :)
