### ISSUE TITLE
Will the arm64 runtime for linux work for the arm64 Android?

### ISSUE THREAD

**Issue by engineer1109** [longjunyu2/MCinaBox#103]
I have a computer with arm64 cpu.
System is Nvidia Tegra Ubuntu 18.04.
If I build the runtime so, will it work for the arm64 Android ?
Have anyone tried?

**Comment by longjunyu2** [comment]
yes.

**Comment by longjunyu2** [comment]
use Android NDK standalone toochain to build them.

**Comment by longjunyu2** [comment]
any questions about building?
