### ISSUE TITLE
Telling me to install runtime when I already did

### ISSUE THREAD

**Issue by SpinnerChris** [longjunyu2/MCinaBox#105]
I compressed the runtime folder from my PC into .tar.xz like it told me to and I imported it and it said succeeded but when I go to management after installing a version it is still telling me to install runtime. I tried restarting the app too.
![Screenshot_20200420-133217 1](https://user-images.githubusercontent.com/50427260/79786667-7344f780-830b-11ea-93c3-51dfa21ae92e.png)
![Screenshot_20200420-133225 1](https://user-images.githubusercontent.com/50427260/79786751-91125c80-830b-11ea-9480-20b9c275438c.png)

**Comment by gabbosta** [comment]
Use the runtime pack that is downloaded from version 0.1.0 of mcinabox

**Comment by SpinnerChris** [comment]
Okay I did, but now after that it wants me to set up the virtual keyboard which is really hard. Whenever I set the position and color and width and height it doesn't appear on the screen to drag around.

**Comment by longjunyu2** [comment]
height 50 width 50. and x:50 y:50 will be useful
