### ISSUE TITLE
GPlay Publishing

### ISSUE THREAD

**Issue by artdeell** [longjunyu2/MCinaBox#107]
Hey! Your app is pretty good for someone.
So, I think: why not publish it to Google Play?
I have a GPlay Developer account, so I can publish it if you want.

But there's a few things to do before publishing, like:
 1. Add auto-download for Runtime Packs
 2. Fix some typos in current translations (i found at least one: when game is downloading, text on button is "CANCLE" instead of "CANCEL")
 2. Add the ability to install Runtime Paks and Forge from anywhere.

I have a choice: publish PojavLauncher or MCinaBox. I can publish both of course, but I don't know from which i should start. 
This launcher is pretty much ready except what I mentioned
PojavLauncher still needs some tiny modifications like logos changing and version filtering, soo
I don't know.
Waiting for response!

**Comment by artdeell** [comment]
@longjunyu2

**Comment by longjunyu2** [comment]
Thank you for your advice, but I'm in school now. I don't have time to continue to develop this project. It's about 80 days away. So I can't improve the project now. Thank you very much.

**Comment by CosineMath** [comment]
PojavLauncher recommended for publishing. As is mentioned in other issues, MCinabox dosen't have 64-bit native libraries. So we need more time for improving MCinabox.

**Comment by LegacyGamerHD** [comment]
@CosineMath  the latest pojav launcher doesn't have 64 bit libs

**Comment by longjunyu2** [comment]
MCinaBox 计划支持自己的插件，便于扩展功能，还有很多的计划

**Comment by gabbosta** [comment]
@longjunyu2 plz Take these commits you added to the master and close the 0.1.4 apk right away
