### ISSUE TITLE
Mods crash app

### ISSUE THREAD

**Issue by blissband123** [longjunyu2/MCinaBox#108]
Everytime i add a mod to the mod folder and start it just crashes the app

**Comment by LegacyGamerHD** [comment]
Yes expected because it's arm device not a 86x

**Comment by longjunyu2** [comment]
have you edited the /sdcard/MCinaBox/.minecraft/config/splash.properties ?

**Comment by blissband123** [comment]
> have you edited the /sdcard/MCinaBox/.minecraft/config/splash.properties ?

Yes i did

**Comment by CosineMath** [comment]
> 
> 
> Yes expected because it's arm device not a 86x
Almost all mods are written in Java, so the crash is not related to cpu architecture. In fact we have tested some Forge mods and they work fine.

**Comment by by-scott** [comment]
> > 可以预期，因为它是手臂设备而不是86x
> 
> 几乎所有的mod都是用Java编写的，因此崩溃与cpu架构无关。实际上，我们已经测试了一些Forge mod，并且它们工作正常。

附议

**Comment by blissband123** [comment]
Could u guys fix it in the next update

**Comment by by-scott** [comment]
> Could u guys fix it in the next update

I suggest you provide them with the your mod and program running logs. This can help them better find the cause of the problem.

**Comment by blissband123** [comment]
I figuard it out u cant use core mods

**Comment by Sergii03** [comment]
How to fix it?
