### ISSUE TITLE
导入键盘布局崩溃，他们自己做的也会崩溃。

### ISSUE THREAD

**Issue by CPXMC** [longjunyu2/MCinaBox#11]

**Comment by yejunjie10311031** [comment]
用我的，
![Screenshot_20200401_143757_com aof mcinabox](https://user-images.githubusercontent.com/62139629/78124978-f4d9f180-73ff-11ea-9469-6bc7f6e0cbf4.jpg)
 链接:https://pan.baidu.com/s/1Z8EUWIE-IxrwtaLHXLV6yQ 提取码:r0ig

**Comment by CPXMC** [comment]
我没问题

**Comment by CPXMC** [comment]
> 用我的，
> ![Screenshot_20200401_143757_com aof mcinabox](https://user-images.githubusercontent.com/62139629/78124978-f4d9f180-73ff-11ea-9469-6bc7f6e0cbf4.jpg)
>  链接:[https://pan.baidu.com/s/1Z8EUWIE-IxrwtaLHXLV6yQ 提取码:r0ig](https://pan.baidu.com/s/1Z8EUWIE-IxrwtaLHXLV6yQ%C2%A0%E6%8F%90%E5%8F%96%E7%A0%81:r0ig)

我没问题
