### ISSUE TITLE
哈哈哈克隆仓库之后初始化项目花了我1h29m 顺便建议升级gradle版本

### ISSUE THREAD

**Issue by xfqwdsj** [longjunyu2/MCinaBox#114]
![image](https://user-images.githubusercontent.com/37076189/80180050-71917180-8634-11ea-93ff-1bde88eb5612.png)
Gradle版本貌似有些旧了 考虑升级吗？

**Comment by artdeell** [comment]
这不是Gradle构建系统。 它是CMake，用于构建本机

**Comment by longjunyu2** [comment]
项目开始时使用的gradle应该是5.x吧，我觉得等到必要的时候再升级。升级gradle一般发生在Android Studio不再支持旧版本gradle时。
