### ISSUE TITLE
0.1.4

### ISSUE THREAD

**Issue by gabbosta** [longjunyu2/MCinaBox#116]
When mcinabox version 0.1.4 will be released?

**Comment by longjunyu2** [comment]
Maybe on 2nd, May.

**Comment by gabbosta** [comment]
but will there be what again?

**Comment by gabbosta** [comment]
Today is May 2, for you have already been in China, and where is version 0.1.4?

**Comment by LegacyGamerHD** [comment]
@gabbosta if you look you can see he is working on it

**Comment by gabbosta** [comment]
But do you have a deadline to launch, maybe until the 3rd or even the 4th?

**Comment by CosineMath** [comment]
No. Please be patient. We might postpone releasing next version for a long time.

**Comment by gabbosta** [comment]
OK
