### ISSUE TITLE
Minecraft Java Edition Launch scripts.

### ISSUE THREAD

**Issue by AyHa1810** [longjunyu2/MCinaBox#117]
This is some Minecraft Java Edition Launch scripts for Linux. Currently these are for Minecraft 1.15.2. You can edit them for launching any version. But the CP section (libraries) needs to be modified. You need to grab the path to libraries and write them in CP section. Or else it will not work.

Because authtoken changes in every session, there are authtoken generator which authenticates your account and generates authtoken of your account at every session.

With only nickname - leul

With Minecraft account support - leul

Fun fact is that if you add --demo in java commandline options, it launches Minecraft as a demo mode.

**Comment by AyHa1810** [comment]
And also, I'm really, REALLY sorry Mojang for making pirated launcher. :D

**Comment by AyHa1810** [comment]
If you are going to include this to the app, you should set CP for auto detecting libraries. MINECRAFT_VERSION is for version and ASSETINDEX is for the assets/indexes/1.xx.json. But you only need to set the filename without the extension. MINECRAFT_LOGIN, MINECRAFT USERNAME and MINECRAFT_PASSWORD are the personal information. And under $JAVA, you can insert java commandline options or arguments.

**Comment by AyHa1810** [comment]
The script with only nickname doesn't require authtoken generator and Minecraft account because it launches Minecraft only with the given nickname.

**Comment by artdeell** [comment]
Why use scripts? Launcher is designed to generate the arguments automatically, and it can inject something that you want. (JVM arguments field)

**Comment by AyHa1810** [comment]
Lol I'm sorry for the mistakes in the scripts.
The scripts will not work.
