### ISSUE TITLE
什么时候能够在软件内删除游戏版本 

### ISSUE THREAD

**Issue by CPXMC** [longjunyu2/MCinaBox#12]

**Comment by longjunyu2** [comment]
删除游戏版本是一个不安全的操作，有的时候甚至是误操作。所以即使添加删除功能，，也仅仅是删除主文件，不计划支持删除库文件。

**Comment by CPXMC** [comment]
> 删除游戏版本是一个不安全的操作，有的时候甚至是误操作。所以即使添加删除功能，，也仅仅是删除主文件，不计划支持删除库文件。

光删核心文件就够了

**Comment by longjunyu2** [comment]
另外如果多版本依赖同一个库，正确的处理库文件显然是相当重要的，往往一个库文件失效，会导致多个版本失效。我觉得删除敏感文件的操作应该由用户手动操作。

**Comment by longjunyu2** [comment]
好的，这个当然会支持的。

**Comment by CPXMC** [comment]
> 好的，这个当然会支持的。

问一下HMCL是不是也是这样删除游戏版本的？

**Comment by longjunyu2** [comment]
不清楚




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CPXMC"<notifications@github.com&gt;; 
发送时间: 2020年4月1日(星期三) 下午2:23
收件人: "longjunyu2/MCinaBox"<MCinaBox@noreply.github.com&gt;; 
抄送: "飞龙在天"<877730493@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [longjunyu2/MCinaBox] 什么时候能够在软件内删除游戏版本  (#12)





  
好的，这个当然会支持的。
  
问一下HMCL是不是也是这样删除游戏版本的？

**Comment by CPXMC** [comment]
> 不清楚
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CPXMC"<notifications@github.com&gt;; 发送时间: 2020年4月1日(星期三) 下午2:23 收件人: "longjunyu2/MCinaBox"<MCinaBox@noreply.github.com&gt;; 抄送: "飞龙在天"<877730493@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [longjunyu2/MCinaBox] 什么时候能够在软件内删除游戏版本 (#12) 好的，这个当然会支持的。 问一下HMCL是不是也是这样删除游戏版本的？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

emmmmmm
