### ISSUE TITLE
Where can i download a keyboard setup file for it. I cant a

### ISSUE THREAD

**Issue by glitchedmc** [longjunyu2/MCinaBox#126]
Where can i download a keyboard layout file or atleast a pic of a sample layout so ik what im doing...

**Comment by LegacyGamerHD** [comment]
Here a basic layout
[layout.zip](https://github.com/longjunyu2/MCinaBox/files/4563218/layout.zip)

**Comment by glitchedmc** [comment]
Thank u. Closing this issue. May reopen if i have problems
