### ISSUE TITLE
运行远古版本崩溃，带日志

### ISSUE THREAD

**Issue by CPXMC** [longjunyu2/MCinaBox#13]
[boat_output.txt](https://github.com/longjunyu2/MCinaBox/files/4413180/boat_output.txt)

**Comment by longjunyu2** [comment]
启动器配置错误，请检查内存大小，多重试几次。

**Comment by longjunyu2** [comment]
远古版好像存在一个X11 Not Found的问题，待解决！

**Comment by longjunyu2** [comment]
这个问题也出现在大多数 1.6以下的版本
