### ISSUE TITLE
Texture and text display error

### ISSUE THREAD

**Issue by huohei250894** [longjunyu2/MCinaBox#132]
When I was playing hypixel, some of the texture of the blockss (like boxes) did not display properly
![Screenshot_2020-05-02-16-57-40-883_com aof mcinabox](https://user-images.githubusercontent.com/16839488/80859969-34158f80-8c97-11ea-803c-456fe89409e9.jpg)
![Screenshot_2020-05-02-16-58-07-841_com aof mcinabox](https://user-images.githubusercontent.com/16839488/80859971-35df5300-8c97-11ea-9e1c-7177a71da900.jpg)
![Screenshot_2020-05-02-16-58-16-862_com aof mcinabox](https://user-images.githubusercontent.com/16839488/80859972-3677e980-8c97-11ea-950e-dfa256370a22.jpg)
 and the text did not display when I entered places with more people.
![Screenshot_2020-05-02-17-00-41-169_com aof mcinabox](https://user-images.githubusercontent.com/16839488/80859981-4099e800-8c97-11ea-9686-5e3c6f9ad295.jpg)

**Comment by artdeell** [comment]
Maybe your phone's GPU just runs out of memory.

**Comment by artdeell** [comment]
Also always remember: Minecraft is designed for PC OpenGL. Android has only OpenGL ES, so commands are wrapped and something may differ between PC GL and wrapped GL.

**Comment by HomieBigSmoke** [comment]
How did u manage to get in a server?

**Comment by FrankOu2001** [comment]
> How did u manage to get in a server?

u can refer to https://github.com/longjunyu2/MCinaBox/issues/88

**Comment by FrankOu2001** [comment]
> When I was playing hypixel, some of the texture of the blockss (like boxes) did not display properly
> ![Screenshot_2020-05-02-16-57-40-883_com aof mcinabox](https://user-images.githubusercontent.com/16839488/80859969-34158f80-8c97-11ea-803c-456fe89409e9.jpg)
> ![Screenshot_2020-05-02-16-58-07-841_com aof mcinabox](https://user-images.githubusercontent.com/16839488/80859971-35df5300-8c97-11ea-9e1c-7177a71da900.jpg)
> ![Screenshot_2020-05-02-16-58-16-862_com aof mcinabox](https://user-images.githubusercontent.com/16839488/80859972-3677e980-8c97-11ea-950e-dfa256370a22.jpg)
> and the text did not display when I entered places with more people.
> ![Screenshot_2020-05-02-17-00-41-169_com aof mcinabox](https://user-images.githubusercontent.com/16839488/80859981-4099e800-8c97-11ea-9686-5e3c6f9ad295.jpg)

I am very sorry to answer your question so lately. You can give it ashot to turn Mipmap levels into Off

**Comment by FrankOu2001** [comment]
> When I was playing hypixel, some of the texture of the blockss (like boxes) did not display properly
> ![Screenshot_2020-05-02-16-57-40-883_com aof mcinabox](https://user-images.githubusercontent.com/16839488/80859969-34158f80-8c97-11ea-803c-456fe89409e9.jpg)
> ![Screenshot_2020-05-02-16-58-07-841_com aof mcinabox](https://user-images.githubusercontent.com/16839488/80859971-35df5300-8c97-11ea-9e1c-7177a71da900.jpg)
> ![Screenshot_2020-05-02-16-58-16-862_com aof mcinabox](https://user-images.githubusercontent.com/16839488/80859972-3677e980-8c97-11ea-950e-dfa256370a22.jpg)
> and the text did not display when I entered places with more people.
> ![Screenshot_2020-05-02-17-00-41-169_com aof mcinabox](https://user-images.githubusercontent.com/16839488/80859981-4099e800-8c97-11ea-9686-5e3c6f9ad295.jpg)

If the version you are playing is 1.15.2, you should turn mipmap levels into 3
