### ISSUE TITLE
App Crash On aarch64 device

### ISSUE THREAD

**Issue by BayuBatam2008** [longjunyu2/MCinaBox#133]

**Comment by BayuBatam2008** [comment]
App Crash on my device
My Device Info =
Android Version: 8.1.0
API Level: 27
Build ID: CPH1909EX_11_A.37
Java VM: ART 2.1.0
OpenGL ES: 3.2
Kernel Architecture: aarch64
Kernel Version: 4.9.77+ (1586659711)

**Comment by LegacyGamerHD** [comment]
might be your android version

**Comment by LegacyGamerHD** [comment]
it works for me with android 10

**Comment by BayuBatam2008** [comment]
But the Android Version of My Phone and the Security Update are the latest

**Comment by LegacyGamerHD** [comment]
@BayuBatam2008 security updates hase nottring todo with it its about the android api

**Comment by BayuBatam2008** [comment]
So what can I do?

**Comment by valetzx** [comment]
please may i ask where aarch64 can download

**Comment by artdeell** [comment]
> But the Android Version of My Phone and the Security Update are the latest

"latest" means latest for your phone. Usually manufacturer stops doing updates for some old phones.
