### ISSUE TITLE
Minecraft Authtoken generator

### ISSUE THREAD

**Issue by AyHa1810** [longjunyu2/MCinaBox#135]
Hey, I have found some Minecraft Authentication Token generation. I don't know if it's work or not. This is for linux.

`MINECRAFT_ATOKEN="$(\`

`curl -i \`

`-H "Accept:application/json" \`

`-H "content-Type:application/json" \`

`https://authserver.mojang.com/authenticate \`

`-X POST \`

`--data '{"agent": {"name": "Minecraft","version": 1}, "username": "'$EMAIL'", "password": "'$PASSWORD'", "clientToken": "'$MINECRAFT_CLIENTTOKEN'" }' \`

`| sed '/accessToken":"/!d;s//&\n/;s/.*\n//;:a;/",/bb;$!{n;ba};:b;s//\n&/;P;D' \`

`)"`

**Comment by artdeell** [comment]
I think @longjunyu2 don't need to re-implement all of the aut algorithms. Pretty much all info about Minecraft( for programmers at least) is stored at https://wiki.vg website

**Comment by longjunyu2** [comment]
ok
