### ISSUE TITLE
0.1.3 crahes when launch

### ISSUE THREAD

**Issue by owenraihan** [longjunyu2/MCinaBox#136]

**Comment by owenraihan** [comment]
I mean I cant install it says app not installer

**Comment by artdeell** [comment]
This is not an issue of app. It maybe caused because:
 1. Your phone ran out of storage memory
 2. Your GPU doesn't support OpenGL ES 2.0
 3. You have an app with simillar package name
 4. You have installed debug versions of MCinaBox

**Comment by lizeyan200711** [comment]
v1签名问题？

**Comment by longjunyu2** [comment]
v1 closed.
