### ISSUE TITLE
Game sometimes crash when launching

### ISSUE THREAD

**Issue by owenraihan** [longjunyu2/MCinaBox#137]
first time launch is good but second launch crashed the game and need to wait for like a hour to launch back normally

Oppo F1f
5.0

**Comment by artdeell** [comment]
Maybe because your RAM is going low on second launch and then frees up after a hour?

**Comment by longjunyu2** [comment]
is it solved?Can this issue be closed?

**Comment by owenraihan** [comment]
yes I increase the ram
