### ISSUE TITLE
Don't working to play newest versions...😥

### ISSUE THREAD

**Issue by Enatlife** [longjunyu2/MCinaBox#142]
It doesn't work to play newer versions, when I enter, it immediately pulls me out and says that I have the keyboard turned off! Please fix it because I want to play the new versions too! 🙏🙏🙏

**Comment by FrankOu2001** [comment]
u can refer 2 https://github.com/longjunyu2/MCinaBox/issues/24

**Comment by Enatlife** [comment]
The game crashes when I enter the newer versions and tells me that the keyboard does not work

**Comment by FrankOu2001** [comment]
You can create a new keyboard in virtual keyboard setting to solve this problem
