### ISSUE TITLE
Oracle java runtime pack

### ISSUE THREAD

**Issue by AyHa1810** [longjunyu2/MCinaBox#144]
Make aarch64 pack from this oracle java packages or get the source code to modify it for support in Android. 
[https://github.com/frekele/oracle-java](https://github.com/frekele/oracle-java) 
It contains both binaries and sources.

**Comment by AyHa1810** [comment]
For latest source code, try to search for src.zip somewhere in jdk binary folder (C:/Program Files/Java/8u231/) in windows. I don't know exactly where it is located.

**Comment by longjunyu2** [comment]
Oracle Java is not open source.

**Comment by FrankOu2001** [comment]
I don't know have you read the JDK8 README .
It says that this source code is provided for informational purposes only, to help developers learn and use the Java programming language. These files do not include platform-specific implementation code and cannot be used to rebuild the class libraries.

**Comment by FrankOu2001** [comment]
The code you said can't build a jdk or jre

**Comment by artdeell** [comment]
That's not Java VM sources, and you can't build Java from them.

вс, 10 мая 2020 г., 07:07 AyHa1810 <notifications@github.com>:
