### ISSUE TITLE
1.15.2 unable to install Forge

### ISSUE THREAD

**Issue by Eric-Joker** [longjunyu2/MCinaBox#145]
给1.15.2安装forge时提示下载失败

**Comment by FrankOu2001** [comment]
下载提示失败没事，反正1.13以上的forge都没法运行😂

**Comment by Eric-Joker** [comment]
作者大大，能不能改一下啊，我现在只想在手机运行1.15.3forge，蟹蟹

**Comment by Eric-Joker** [comment]
作者大大，能不能改一下啊，我现在只想在手机运行1.15.2forge，蟹蟹

**Comment by longjunyu2** [comment]
1.13以上均不能运行forge。更改的计划待定。

**Comment by FrankOu2001** [comment]
这跟我们没关系，我们也无能为力。。。。
