### ISSUE TITLE
安卓10无法运行游戏

### ISSUE THREAD

**Issue by hmcy** [longjunyu2/MCinaBox#147]
小米8  MIUI11.0.7稳定版  安卓10
软件能正常打开，正常下载游戏版本，但是一运行就闪回启动游戏的界面，希望能解决

**Comment by FrankOu2001** [comment]
同为小米8 MIUI11 安卓10 软件游戏都能正常运行。右上角可以查看哪些没配置好，应该是你自己的问题

**Comment by hmcy** [comment]
都配置好了，显示蓝色的叹号，就是进不去游戏

**Comment by hmcy** [comment]
点击启动游戏，白屏一下，然后就返回启动界面了

**Comment by longjunyu2** [comment]
游戏版本？

**Comment by hmcy** [comment]
重置了手机，现在可以用了

**Comment by hmcy** [comment]
现在的问题是游戏里面不能打字，工具条的那个键盘没用
