### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by notaseel** [longjunyu2/MCinaBox#150]
Sometimes all the letters just go black and the only way to fix it is to restart the game, but it does the same thing after a few minutes. I tried switching to unicode font but after a few minutes the same thing happened but instead of black unicode turns white. This is really annoying since I'm on Hypixel and I can't read anything when it happens.

**Comment by FrankOu2001** [comment]
Turn off  mipmaplevels in video settings.
This problem has been written in README.😑
