### ISSUE TITLE
Download/Master is not found.

### ISSUE THREAD

**Issue by Nabrious** [longjunyu2/MCinaBox#153]
Github shows a 404 page, which means I can't download it sadly.

**Comment by longjunyu2** [comment]
I have not found similar problem when downloaded...

**Comment by Nabrious** [comment]
![Screenshot_2020-05-17-16-29-23](https://user-images.githubusercontent.com/65465862/82152798-11bd6d80-9864-11ea-95bf-e2076da6a912.png)
Proof i guess.

**Comment by longjunyu2** [comment]
https://github.com/longjunyu2/MCinaBox/releases
