### ISSUE TITLE
Sound issue 

### ISSUE THREAD

**Issue by yichifauzi** [longjunyu2/MCinaBox#154]
Sounds issue with forge and optifine 1.12.2
Can't heard every sound on game
and F3 + T doesn't work

**Comment by SakiNawak** [comment]
Same thing for Minecraft 1.9.4 with forge and optifine

**Comment by pedrosouzabrasil** [comment]
Anyone now?please share ???

**Comment by yichifauzi** [comment]
@longjunyu2

**Comment by pedrosouzabrasil** [comment]
#94
