### ISSUE TITLE
is this project dead

### ISSUE THREAD

**Issue by LegacyGamerHD** [longjunyu2/MCinaBox#158]
i mean there arnt any releases and 0.1.4 got delayed 2 times

**Comment by artdeell** [comment]
literally yes

**Comment by LegacyGamerHD** [comment]
@artdeell what should i use now for MC Java client

**Comment by LegacyGamerHD** [comment]
For android

**Comment by Donovan22** [comment]
The developer of this project said that he is rewriting a lot of it to make it more modular. He also said that he is studying for a big test. I would wait a little while before calling this project dead.

**Comment by Donovan22** [comment]
I also know of no alternatives to this project, other than the older similar ones that this project credits in the readme.

**Comment by artdeell** [comment]
> I also know of no alternatives to this project, other than the older similar ones that this project credits in the readme.

There is a launcher called PojavLauncher, but we are preparing v3 release, so current support is very limited (up to 1.11.2)

**Comment by CosineMath** [comment]
No... It is just suspended (because longjunyu is studying hard for an important test called gaokao in China). 

I have updated the backend libraries (Boat, lwjgl2/3 and glfw) for MCinaBox, but I might not commit or release on github until longjunyu comes back...

**Comment by BryleHelll** [comment]
The gaokao is China's notoriously tough entrance exam, which can also get you into western universities — check out its punishing questions. China's version of the American SAT and British A-level exams takes place in June every year. It's called the gaokao, and is known as one of the toughest exams in the world
