### ISSUE TITLE
Why do Minecraft 1.13 and above versions crash?

### ISSUE THREAD

**Issue by Vincysuper07** [longjunyu2/MCinaBox#170]
When I try to open Minecraft 1.13 and above versions and I start, the game crashes. How can I fix this?

**Comment by LegacyGamerHD** [comment]
read readme

**Comment by LegacyGamerHD** [comment]
its a bug

**Comment by Vincysuper07** [comment]
Oh ok

**Comment by CosineMath** [comment]
Minecraft 1.15+ works. There are some bugs for Minecraft 1.13 - 1.14.

**Comment by Vincysuper07** [comment]
Oh, thank you

**Comment by Vincysuper07** [comment]
I just checked, 1.15 and above versions don't work

**Comment by lizeyan200711** [comment]
> 我刚刚检查过，1.15及以上版本不

在20w14上起作用
