### ISSUE TITLE
最新快照版运行成功了，非常流畅，贴图也没有bug，就是鼠标一动就位移，一转动视角就会破坏方块

### ISSUE THREAD

**Issue by yejunjie10311031** [longjunyu2/MCinaBox#18]
![Screenshot_20200401_214942_com aof mcinabox](https://user-images.githubusercontent.com/62139629/78159006-82820500-7431-11ea-9a39-31b626e398d3.jpg)
![Screenshot_20200401_233942_com aof mcinabox](https://user-images.githubusercontent.com/62139629/78159024-86158c00-7431-11ea-80c6-a4c24cc76105.jpg)
![Screenshot_20200401_233955_com aof mcinabox](https://user-images.githubusercontent.com/62139629/78159034-89107c80-7431-11ea-94e0-4b3787c5af0c.jpg)
![Screenshot_20200401_234112_com aof mcinabox](https://user-images.githubusercontent.com/62139629/78159039-8ada4000-7431-11ea-9ec6-21740fb67891.jpg)
![Uploading Screenshot_20200401_234508_com.aof.mcinabox.jpg…]()

**Comment by longjunyu2** [comment]
了解
