### ISSUE TITLE
aarch64_runtime_20200601

### ISSUE THREAD

**Issue by AyHa1810** [longjunyu2/MCinaBox#183]
Yes! I made a working aarch64 runtime pack because of my stupidity! XD! I made it by extracting aarch32 runtime pack and then replacing OpenJDK aarch32 linux binaries with OpenJDK aarch64 linux binaries I got [from here](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u252-b09/OpenJDK8U-jre_aarch64_linux_hotspot_8u252b09.tar.gz) ! I tested it in 1.12.2 and the sound now works! But I don't know if you should use it or not. Note that it does not fixes 1.14.x or later OpenGL.
You can download the pack from here - [aarch64_runtime_20200601.tar.xz](https://drive.google.com/file/d/1KXb4PaorWi4Fq18mEJwnP5Ns_axsPhdp/view?usp=drivesdk) 
If it doesn't work, then, nevermind.

**Comment by engineer1109** [comment]
sounds good. Let me have a try.

**Comment by LegacyGamerHD** [comment]
@AyHa1810 crashes when I start minecraft

**Comment by AyHa1810** [comment]
> @AyHa1810 crashes when I start minecraft

I said I can't do anything about it. And this is for only aarch64 architecture. I am sorry but I don't know much about programming.
I only changed the runtime pack but not the native lwjgl and OpenGL libraries. Btw it fixed the sound issue in 1.12.2 on my phone.

Here is the file hierarchy of the pack.
<Architecture>_runtime_<date>.tar.xz

> j2re-image

> lwjgl2

> lwjgl3

> LibGL.so.1

> Libopenal.so.1

> pack.json

**Comment by LegacyGamerHD** [comment]
> > @AyHa1810 crashes when I start minecraft
> 
> I said I can't do anything about it. And this is for only aarch64 architecture. I am sorry but I don't know much about programming.
> I only changed the runtime pack but not the native lwjgl and OpenGL libraries. Btw it fixed the sound issue in 1.12.2 on my phone.
> 
> Here is the file hierarchy of the pack.
> Architecture_runtime_date.tar.xz
> 
> > j2re-image
> > > Linux jdk binaries
> 
> > lwjgl2
> > > liblwjgl.so
> > > lwjgl.jar
> > > lwjgl_util.jar
> 
> > lwjgl3
> > > libglfw.so
> > > liblwjgl.so
> > > liblwjgl_opengl.so
> > > liblwjgl_opengles.so
> > > liblwjgl_stb.so
> > > liblwjgl_tinyfd.so
> > > lwjgl.jar
> > > lwjgl-egl.jar
> > > lwjgl-glfw.jar
> > > lwjgl-jemalloc.jar
> > > lwjgl-openal.jar
> > > lwjgl-opengl.jar
> > > lwjgl-opengles.jar
> > > lwjgl-stb.jar
> > > lwjgl-tinyfd.jar
> 
> > LibGL.so.1
> 
> > Libopenal.so.1
> 
> > pack.json

Again my phone is aarch64 its a Galaxy s9+

**Comment by LegacyGamerHD** [comment]
But i think i get why it does that if changed some libs

**Comment by engineer1109** [comment]
you mean lwjgl and glfw is 32 ?

**Comment by LegacyGamerHD** [comment]
Welk the Java is also aarch32 i got it working show a screen shot if have it different on f3
![Screenshot_20200602-072913](https://user-images.githubusercontent.com/25864932/83483827-da75d000-a4a3-11ea-8d54-f1efb67e6b33.png)

**Comment by AyHa1810** [comment]
> Welk the Java is also aarch32 i got it working show a screen shot if have it different on f3
> ![Screenshot_20200602-072913](https://user-images.githubusercontent.com/25864932/83483827-da75d000-a4a3-11ea-8d54-f1efb67e6b33.png)

Well, I know that native programs requires a defined architecture and/or os. So, it means that jre aarch32 doesn't have any defined architecture between aarch32 and aarch64.So, it can run on aarch64 architecture but not in others.

**Comment by AyHa1810** [comment]
Or if there was a problem with it, then I am closing the issue if you want.

**Comment by AyHa1810** [comment]
> you mean lwjgl and glfw is 32 ?

Yes, the native lwjgl and glfw is aarch32. Sorry, but I don't have much knowledge about programming.

**Comment by CosineMath** [comment]
The binaries in runtime pack should be specially compiled for Android. The ones for common GNU/Linux will not work.

**Comment by AyHa1810** [comment]
> The binaries in runtime pack should be specially compiled for Android. The ones for common GNU/Linux will not work.

Isn't Android a totally modified version of linux? I would like to say no but actually yes. And don't worry, if it doesn't work on your phone, then it means that it only works on my phone.

**Comment by LegacyGamerHD** [comment]
still says aarch32 aslo it doesnt clean out the runtime so your running the old runtime @AyHa1810 and if not show me screen shot in f3

**Comment by KUALALUM** [comment]
@AyHa1810  why you deleted the runtime i want it

**Comment by engineer1109** [comment]
@KUALALUM  It will not work

**Comment by vladtheplay** [comment]
AyHa1810 
i can't download aarch64_runtime_20200601 file your link is not valid

**Comment by FreddyFeuerstein** [comment]
> The binaries in runtime pack should be specially compiled for Android. The ones for common GNU/Linux will not work.

I tried this on android x86 on an old intel tabled and it worked.
