### ISSUE TITLE
Wen i download a version it stops downloading (i have 1.9 gb) 

### ISSUE THREAD

**Issue by li0n3n** [longjunyu2/MCinaBox#187]
Idk why but it stops from downloading i waited but still it stops at like 72% and its not downloading the version anymore it remains stuck at 2/4 72% but i fell like it stops random one time ut stoped at 4/4 99% , and if i press cancel and try to download the version again it  gets over the number wen it stoped and it starts loading again but its now downloading anything it stops at 2/4 and after it loads and it says that it was downloaded it crashed and wen i look in my files (i have show hidden files on) and wen i look at the version folder it only says that there are 2 files (idk if it need to be 4 files bc its 4/4 and not 2/2 ) also i did everything else i made an user i put a keyboard template imported that thing i forgot how its called (i have 1,9 gb remaining or more also one time it worked and the version downloaded but wen i was making a world/entering in a world the world was not loading and i changed the memory thing from like 200 mg to 1024 mg but the same thing happen) also my phone is not realy that good but not that bad  its and samsung galaxy j3 2017 it runs cod mobile so it is good but bad at the same time bc its a 32 bit phone (soory if i spelled some things wrong)

**Comment by li0n3n** [comment]
Update: i managed to instal the versio  1.12.2 it still takes alot to load but i will change thigs in the setings it still takes alot for the map to load/or its not even loading idk maybe if i use optifine and change somethings in the settings it will load i will still leave tbis open so you guys can se this and fix the downloading problem

**Comment by AyHa1810** [comment]
> Update: i managed to instal the versio 1.12.2 it still takes alot to load but i will change thigs in the setings it still takes alot for the map to load/or its not even loading idk maybe if i use optifine and change somethings in the settings it will load i will still leave tbis open so you guys can se this and fix the downloading problem


> Update: i managed to instal the versio 1.12.2 it still takes alot to load but i will change thigs in the setings it still takes alot for the map to load/or its not even loading idk maybe if i use optifine and change somethings in the settings it will load i will still leave tbis open so you guys can se this and fix the downloading problem

Optifine will only work in forge versions.

**Comment by li0n3n** [comment]
Ok thx
