### ISSUE TITLE
1.15.2 crash

### ISSUE THREAD

**Issue by li0n3n** [longjunyu2/MCinaBox#199]
Wen i launch the game whit the version 1.15.2 the app crashes i alocated 1gb to but i idk why its crashing

**Comment by FrankOu2001** [comment]
The memory you set is too large and the system of your mobile don't allow to give 1gb

**Comment by gabbosta** [comment]
so what would be the proper memory for

**Comment by haohaostudio** [comment]
you gave nth even describe or log..
