### ISSUE TITLE
[Request] English languages 

### ISSUE THREAD

**Issue by LegacyGamerHD** [longjunyu2/MCinaBox#20]
That woeld be nice

**Comment by longjunyu2** [comment]
You are poor in English，so am I.

**Comment by longjunyu2** [comment]
I am working on new Downloader in MCinaBox，I will add English Soon.

**Comment by gabbosta** [comment]
Please add better support to current and 64bit versions

**Comment by LegacyGamerHD** [comment]
@gabbosta stop asking here if have issue dont report it here

**Comment by LegacyGamerHD** [comment]
@longjunyu2 can you add github actions compile and archive a apk on commit
