### ISSUE TITLE
 要求改进：您可以将MCinaBox配置为易于集成为第三方翻译吗？

### ISSUE THREAD

**Issue by artdeell** [longjunyu2/MCinaBox#22]
您是否可以添加语言更改，以便人们可以方便地翻译MCinaBox，而无需对代码进行重大更改。我已经准备好了俄文的翻译，我想以某种方式将其集成到MCinaBOX中

**Comment by longjunyu2** [comment]
I am trying to add multilingual options in the next version, and I will provide a solution for multilingual support addition. Your help will be very effective.

**Comment by gabbosta** [comment]
Put Brazilian Portuguese please
