### ISSUE TITLE
Ram question

### ISSUE THREAD

**Issue by Dergrive** [longjunyu2/MCinaBox#226]
Is there a limit in how much ram I can give? Because I have 8G ram but I can only give 800 Mb, if I go higher it crashes instantly it helps with lag so if is already fixed in future versions im ok with that. Thanks for listening.

**Comment by bghyt** [comment]
> Is there a limit in how much ram I can give? Because I have 8G ram but I can only give 800 Mb, if I go higher it crashes instantly it helps with lag so if is already fixed in future versions im ok with that. Thanks for listening.

Android has a phone imposed RAM limit around 700-900mb for modern phones (the less ram you have i guess the smaller the number) if it is set any higher it will crash the app, currently the dev is looking for a solution around this, i find 900mb of ram in 1.12.2 and 1.7.10 work really well, you can install optifine on your PC and drag over the 1.12.2 or 1.7.10 version folder and it will work in app if you want to help with any lag on your phone, you can also turn down in-game settings to help with lag too.

**Comment by Dergrive** [comment]
I was right about the limit them... Ok thanks and yeah i tried different types of mods in different versions of them. There are a lot of important mods like (core mods) that dont work but overall is a good progress.

**Comment by bghyt** [comment]
you can have one or two mods just don't get greedy, and keep in mind the mod might cause a crash too, so i tend to keep it to optifine.

**Comment by Dergrive** [comment]
With effort i did run 43 mods and was running smoothly. It in fact works well

**Comment by Dergrive** [comment]
If i have time i can release the pack for everyone but it needs more twisting

**Comment by Dergrive** [comment]
All good
