### ISSUE TITLE
App crash at start

### ISSUE THREAD

**Issue by OzzyFox** [longjunyu2/MCinaBox#246]
I install all staff and start play at vanilla 1.12.2 with allocated 1024 mb. Game had chashed and when i start  MCinaBox it crashed too. Reboot doesnt help. I can reistall app but i did that lke 3 times and want to find how to fix this. Oneplus 8 pro 12/256 10 andoid

**Comment by piotrek94692** [comment]
Have you tried allocating less RAM? You can't allocate more RAM than free RAM.

**Comment by OzzyFox** [comment]
REinstall app (again) and don't install x64, witch don't work. MC crashes sometimes, but, that's like normal) Waiting 64 Java update)
If app will breaks again i will mark it there (new issue)
P.s. At 1.12.2 vanilla at 2K resolution like 90-180 FPS at 7 chunks, wow
