### ISSUE TITLE
Add Language Settings please and how to start

### ISSUE THREAD

**Issue by FranzelDamasco909** [longjunyu2/MCinaBox#26]
I try to play the latest version of Minecraft Java and i don't know how to start. Please add a language settings

**Comment by longjunyu2** [comment]
Have finished to support English.But the next release version still needs some time.

**Comment by gabbosta** [comment]
When will the new version be released

**Comment by longjunyu2** [comment]
I need some time to make sure that the app runs will.Just in one day.

**Comment by gabbosta** [comment]
And when will you add the runtime to the arm64?

**Comment by longjunyu2** [comment]
There is no way to compile openjdk for arm64 yet. I am discussing the solution with other developers

**Comment by gabbosta** [comment]
Please don't take too long because my phone runs this arm and I uninstalled this Minecraft because some versions are not entering because of that

**Comment by longjunyu2** [comment]
OK.
