### ISSUE TITLE
Dark Minecraft

### ISSUE THREAD

**Issue by themen098s** [longjunyu2/MCinaBox#262]
I successfully launched Minecraft, but most of the textures are black. My settings are on fast, an mipmap 0.
![Screenshot_2020-07-19-00-31-46-126_com aof mcinabox](https://user-images.githubusercontent.com/41344606/87863120-f8b26500-c957-11ea-823e-a07469c185bc.jpg)
[boat_output.txt](https://github.com/longjunyu2/MCinaBox/files/4942828/boat_output.txt)

**Comment by bghyt** [comment]
for 1.13 and above it's known that you need a mipmap of 1 for below 1.13 it needs to be 0, at least look at the ongoing issues before posting please.

**Comment by qaz6750** [comment]
There is a rendering error in the 1.13+ version. Installing HD repair will also experience many repairs. If it is not useful, you can try to reopen the value of about 1 to 4.
