### ISSUE TITLE
Foreground home buttons and notifications bar

### ISSUE THREAD

**Issue by etiennec78** [longjunyu2/MCinaBox#269]
Hi, when I play on Minecraft, my home buttons and my notification bar annoy me because they go over the game and hide the buttons of MCinaBox at the top left of the screen, my hotbar and some buttons in menus.
I am on fireOS (Android 5.1.1) with an Amazon Fire HD 8 6th gen
![Screenshot_2020-07-21-00-42-43](https://user-images.githubusercontent.com/59794011/87993977-28927180-caec-11ea-9751-7a14a27ffbb2.png)

**Comment by Soharuda** [comment]
This is an issue with any tablet. The navbar never goes away

Sent via the Samsung Galaxy S10+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by RuofengX** [comment]
As I know, it's about android immersive mode.
Yet you can use ADB shell to force the system to run a program under immersive mode, just try this code in the ADB shell:
"adb shell settings put global policy_control immersive.full=<APPS_YOU_NEEDS_TO_FULLSCREEN>"
For example:
"adb shell settings put global policy_control immersive.full=apps,-com.google.android.googlequicksearchbox"

**Comment by RuofengX** [comment]
As I know, it's about android immersive mode.
Yet you can use ADB shell to force the system to run a program under immersive mode, just try this code in the ADB shell:
`adb shell settings put global policy_control immersive.full=<APPS_YOU_NEEDS_TO_FULLSCREEN>
`
For example:
`adb shell settings put global policy_control immersive.full=apps,-com.google.android.googlequicksearchbox"
`

**Comment by etiennec78** [comment]
It worked! Thanks
