### ISSUE TITLE
Language options required

### ISSUE THREAD

**Issue by jrxohan** [longjunyu2/MCinaBox#27]
Hello, it is nothing about the app as it is unplayable for users who do not speak the Chinese language like I do who speak Spanish, but a unique translation to English is more profitable since it is better understood, nothing more, and I hope you will add it now.  that this app promises to be good, this is a medium reelevant problem

**Comment by longjunyu2** [comment]
OK,I know.I will do that.

**Comment by jrxohan** [comment]
> OK,I know.I will do that.

Thank you very much your effort is appreciated
