### ISSUE TITLE
Can't Change Language

### ISSUE THREAD

**Issue by AAROHBHAGAT** [longjunyu2/MCinaBox#273]
I can't change the language in-game. It always freezes and immediately crashes right after. Tried everything but it doesn't work. This only happens on the language screen.

**Comment by CloserPopcorn20** [comment]
So, you must to change the lang part of options.txt

**Comment by CloserPopcorn20** [comment]
For example:
lang: ru_RU (I'm from Russia)

**Comment by AAROHBHAGAT** [comment]
Thanks!
