### ISSUE TITLE
Versions 1.12 above crashing always mid game, ticking entity crash

### ISSUE THREAD

**Issue by Jeffhub113** [longjunyu2/MCinaBox#294]
I thought I was gonna be able to play the game properly after fixing no sound cause by forged but then its unplayable suddenly, it crashes when it loads some chunks after moving around the world for a while. Crash log always detect it as ticking entity.
Making a new world doesnt fix the issue. Gonna downgrade to 1.8.9 version, if it still persist on 1.8.9, im just gonna have to buy pocket edition then. I spent most of my days troubleshooting the game that i could have spent time playing for fun.
The launcher is buggy and needs updating especially opengl 2.0 limits the functionality of minecraft unlike opengl 3.

**Comment by Jeffhub113** [comment]
Gonna buy pocket edition, i gave up even version 1.12.2 keeps crashing with same ticking identity error.

**Comment by AyHa1810** [comment]
This app is still in development, so there are a lot of issues. And, transferring Minecraft Java Edition on to Android is difficult. To make it run on Android, it needs java runtime environment, LWJGL and it's native libraries, especially compiled for Android.

**Comment by Jeffhub113** [comment]
> This app is still in development, so there are a lot of issues. And, transferring Minecraft Java Edition on to Android is difficult. To make it run on Android, it needs java runtime environment, LWJGL and it's native libraries, especially compiled for Android.

I understand, i just bought minecraft on android to play it properly instead of my java edition account. Hoping to see the app improve as time goes by. Goodluck to the devs, will be checking out from time to time for some app updates.
