### ISSUE TITLE
Is project Dead?

### ISSUE THREAD

**Issue by BryleHelll** [longjunyu2/MCinaBox#302]
Some people on pojav discord say that mcinabox is dead(even @artdeell ). If no contributor respond it means its dead. This is a test. :)

**Comment by FrankOu2001** [comment]
No, the author is still programing now.I have updated some screenshots on previous issues.However, most of people don't understand Chinese

**Comment by FrankOu2001** [comment]
![-374c4f949251db19](https://user-images.githubusercontent.com/46289742/89712231-21130980-d9c2-11ea-8d4f-5affa163aba3.jpg)

**Comment by FrankOu2001** [comment]
![346c8175d01feca8](https://user-images.githubusercontent.com/46289742/89712238-34be7000-d9c2-11ea-86e2-ffa7f4efbe38.jpg)
This is the screenshot of new virtual keyboard setting.

**Comment by BryleHelll** [comment]
What about a runtime work 4 all android devices
