### ISSUE TITLE
Ram Not more than 1gb on Android ?

### ISSUE THREAD

**Issue by jamo-lcr** [longjunyu2/MCinaBox#305]
Why can't I use more than 1 GB RAM on Android ?
Ist the Code for  the RAM from you or from gradel ?
Could you fix it ?

**Comment by BryleHelll** [comment]
Dont allocate to much ram. It will cause lag. Just balanced like 256 or 512

**Comment by ActiveClosure** [comment]
1328 is the most I got before I crashed.

**Comment by BryleHelll** [comment]
Ok

**Comment by FrankOu2001** [comment]
> Why can't I use more than 1 GB RAM on Android ?
> Ist the Code for the RAM from you or from gradel ?
> Could you fix it ?

We can do nothing about it, because Android system has a restriction about app's ram which can be used. That's to say, different mobiles have different size of ram which can be used for mcinabox.
