### ISSUE TITLE
有没有可能把mc的jar转为dex用安卓原生虚拟机运行？

### ISSUE THREAD

**Issue by plusls** [longjunyu2/MCinaBox#307]
https://stackoverflow.com/questions/8348144/how-to-convert-jar-or-class-to-dex-file

本身不太熟悉安卓和java开发，不知道这样做能否提高性能，总感觉安卓的虚拟机是优化过的会不会好一些

**Comment by FrankOu2001** [comment]
这个不就是board walk嘛

**Comment by plusls** [comment]
orz 太菜了不太了解技术细节，不知道这样是否可行以及能否提升性能

**Comment by AyHa1810** [comment]
I don't think minecraft can run on art/dalvik.

**Comment by plusls** [comment]
I think Mixin may not work normally, but java code should work normally.

**Comment by FrankOu2001** [comment]
你所说的已在[https://github.com/zhuowei/Boardwalk](url)项目中实现。而Mcinaobx就是根据这个项目发展过来的。
这样子理论上能提升性能，但是对于像Forge就没法使用了

**Comment by plusls** [comment]
那是否可以考虑使用Fabric？

**Comment by plusls** [comment]
Fabric使用Mixin，可以先生成Mixin后的class，再转为dex达到支持mod的效果
