### ISSUE TITLE
切屏出去回来游戏关了

### ISSUE THREAD

**Issue by Coloryr** [longjunyu2/MCinaBox#309]
用的是最新版的APP
我启动好了，切屏出去看一眼QQ，然后再切回来，游戏直接关了。
安卓：10
MC：1.16.1

**Comment by AyHa1810** [comment]
The game will crash if you keep it running in background.

**Comment by Coloryr** [comment]
but if in background,the game was still running

**Comment by FrankOu2001** [comment]
这个是boat的锅
