### ISSUE TITLE
建议增加新的运行环境

### ISSUE THREAD

**Issue by Coloryr** [longjunyu2/MCinaBox#311]
建议加个JAVA14的运行环境，
JAVA14效率比JAVA8高不少
如果能的话尽量加一下吧

**Comment by AyHa1810** [comment]
MCinaBox developers need to modify and compile OpenJDK 14's source code for support in Android. OpenJDK 14 linux arm binary will not work on many phones, still if Android is a modified version of linux.

**Comment by Coloryr** [comment]
I will try make one, and try to run on my phone.(hope is work)

**Comment by TSaltedfishKing** [comment]
会增加,但不一定如此
