### ISSUE TITLE
how to get 80+ fps in mcinabox 

### ISSUE THREAD

**Issue by KUALALUM** [longjunyu2/MCinaBox#315]
I have 2.20GB but how 
I already have optifine but my fps still 36,40

**Comment by LegacyGamerHD** [comment]
buying a better phone

**Comment by KUALALUM** [comment]
@LegacyGamerHD HAHAAHAHHAHAHAHAHAHHAHA 



DONT HAVE MONEY

**Comment by LegacyGamerHD** [comment]
> @LegacyGamerHD HAHAAHAHHAHAHAHAHAHHAHA
> 
> DONT HAVE MONEY

Deal with it or get a job

**Comment by KUALALUM** [comment]
> > @LegacyGamerHD HAHAAHAHHAHAHAHAHAHHAHA
> > DONT HAVE MONEY
> 
> Deal with it or get a job

Ok

**Comment by gamecss** [comment]
1.把内存增大 2.把各项设置调到最低 3.降低游戏版本
*终极解决方法：
用电脑玩Minecraft

**Comment by gamecss** [comment]
1. Increase the memory 2. Adjust the settings to the minimum 3. Reduce the game version*The ultimate solution:Play minecraft with computer

**Comment by gamecss** [comment]
1. Increase the memory 2. Adjust the settings to the minimum 3. Reduce the game version
*The ultimate solution:
Play minecraft with computer
