### ISSUE TITLE
how to play mcpc old version in mcinqbox

### ISSUE THREAD

**Issue by KUALALUM** [longjunyu2/MCinaBox#316]
I have install it but it crash 
Can anyone tell me

**Comment by LegacyGamerHD** [comment]
Stop spamming issues as this project is dead as fuck

**Comment by FrankOu2001** [comment]
> Stop spamming issues as this project is dead as fuck

Are you serious???lmao

**Comment by LegacyGamerHD** [comment]
> > Stop spamming issues as this project is dead as fuck
> 
> Are you serious???lmao

yeah its month later no commits also also i get anoyed with such dum qeastions

**Comment by FrankOu2001** [comment]
> > > Stop spamming issues as this project is dead as fuck
> > 
> > 
> > Are you serious???lmao
> 
> @FrankOu2001 yeah its month later no commits also also i get anoyed with such dum qeastions

To tell the truth,  because of those useless questions, the author has already given up viewing issues. lol

**Comment by FrankOu2001** [comment]
In fact , the author is coding and sharing the progress on QQ(a Chinese instant messaging software).

**Comment by LegacyGamerHD** [comment]
> In fact , the author is coding and sharing the progress on QQ(a Chinese instant messaging software).

yes but am not chinese so i cant read or go on that chat

**Comment by FrankOu2001** [comment]
> > In fact , the author is coding and sharing the progress on QQ(a Chinese instant messaging software).
> 
> yes but am not chinese so i cant read or go on that chat

The project is not dead and a new version will be released.
