### ISSUE TITLE
怎么组成一个自己的runtime包？

### ISSUE THREAD

**Issue by gamecss** [longjunyu2/MCinaBox#317]
这个包是怎么解析的

**Comment by gamecss** [comment]
特别是java环境 目录名指的是j2re 可json内指的是openjdk

**Comment by gamecss** [comment]
特别是java环境 目录名指的是j2re 可json内指的是openjdk

**Comment by FrankOu2001** [comment]
先不要管怎么解析的。首先你先得用ndk编译出openjdk,lwjgl,glfw，一点都不好弄，要是好弄的话我们早就推出新的runtime包了。

**Comment by gamecss** [comment]
说的好！我选择用ndk的独立编译链
