### ISSUE TITLE
⬆️[Pre-Release] MCinaBox 0.1.4-pre version:

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [longjunyu2/MCinaBox#318]
What is the Plugin menu option for, and is it possible to install Fabric and of course OptiFine for Minecraft here?

**Comment by admin-elvistrujanovic** [comment]
@MCinaBox Why many of the options in which other versions are running this version does not work because I tried to download a version of the game but it's a blank list, the option to restart the list is not working, it's already out of play, and the Plugin option is also empty but it doesn't work out. It won't create new accounts as if you blocked the user's standard use only for viewing in that version.

**Comment by admin-elvistrujanovic** [comment]
@longjunyu2 Link to pre-release 0.1.4 is here: https://github.com/longjunyu2/MCinaBox/files/4943586/mcinabox-debug.zip

**Comment by FrankOu2001** [comment]
> @longjunyu2 Link to pre-release 0.1.4 is here: https://github.com/longjunyu2/MCinaBox/files/4943586/mcinabox-debug.zip

Where did you get it ?

**Comment by FrankOu2001** [comment]
> @longjunyu2 Why many of the options in which other versions are running this version does not work because I tried to download a version of the game but it's a blank list, the option to restart the list is not working, it's already out of play, and the Plugin option is also empty but it doesn't work out. It won't create new accounts as if you blocked the user's standard use only for viewing in that version.

Because he didn't updated the complete code.

**Comment by FrankOu2001** [comment]
> @longjunyu2 Link to pre-release 0.1.4 is here: https://github.com/longjunyu2/MCinaBox/files/4943586/mcinabox-debug.zip

What's more,  I can told you that the author has never release the apk of  MCinaBox 0.1.4-pre version.

**Comment by admin-elvistrujanovic** [comment]
> > @longjunyu2 Link to pre-release 0.1.4 is here: https://github.com/longjunyu2/MCinaBox/files/4943586/mcinabox-debug.zip
> 
> What's more,  I can told you that the author has never release the apk of  MCinaBox 0.1.4-pre version.

Which then allowed this to give me access when it is in your server hidden for download?

**Comment by gamecss** [comment]
who to found runtime?
