### ISSUE TITLE
mojang account support

### ISSUE THREAD

**Issue by LegacyGamerHD** [longjunyu2/MCinaBox#32]
so i can join servers etc

**Comment by longjunyu2** [comment]
The code now contains the corresponding and load templates needed to validate the server, Next, I will try to add the code related to the login request.Thank you for your issues. There are many things to improve in this project ;)

**Comment by LegacyGamerHD** [comment]
your the best @longjunyu2 i really like this project keep up to good work

**Comment by by-scott** [comment]
> your the best @longjunyu2 i really like this project keep up to good work

Now already supports online login.

**Comment by LegacyGamerHD** [comment]
this is done so i close this
