### ISSUE TITLE
Is it possible/plausible for an iOS port?有可能做iOS的包么

### ISSUE THREAD

**Issue by SZCthebandit** [longjunyu2/MCinaBox#320]
我不懂开发，可是如果不是很费劲的话还是希望能考虑为这个项目增加iOS分支，也不一定要上架Store啦，能放出ipa就可以不越狱加载到苹果设备上了(使用AltStore)。

**Comment by AyHa1810** [comment]
That might be very difficult for contributors.

**Comment by TSaltedfishKing** [comment]
很难

**Comment by FrankOu2001** [comment]
很难，你可以现在开始以此为目标，一点点努力.......

**Comment by TSaltedfishKing** [comment]
网易云深度用户觉得不现实
