### ISSUE TITLE
启动界面展示错误

### ISSUE THREAD

**Issue by feilongproject** [longjunyu2/MCinaBox#324]
在所有准备工作做好之后（包括：创建用户、使用键盘布局、选择游戏版本），并成功启动了游戏（包括原版和forge版本），但启动界面右上角依然会出现红色感叹号标识，点击时出现的框里并未有任何提示，这是一个bug么？

设备：vivo y93 v1818a
系统版本：8.1.0
应用版本：v0.1.3

**Comment by Kotarou2k4** [comment]
If the exclamation mark turn into blue after that then everything is working normally

**Comment by feilongproject** [comment]
> If the exclamation mark turn into blue after that then everything is working normally

No,this is red.

**Comment by TSaltedfishKing** [comment]
emmm,并不是什么大问题
