### ISSUE TITLE
I can't build an apk from your GitHub Source Code

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [longjunyu2/MCinaBox#329]
I installed a Java N-IDE android application that was based on the Android SDK, Android NDK and JDK but did not wanted to run the application. Finds many errors in the underlying code so that it cannot create or use the application. I hope you're working on correcting mistakes.

Link to the application:

[]()https://play.google.com/store/apps/details?id=com.duy.compiler.javanide

**Comment by FrankOu2001** [comment]
You shall built it by Android Studio.

**Comment by FrankOu2001** [comment]
And the lasted code can't be built, because you have to repair some lines if you can make it.

**Comment by SliceCast** [comment]
> I installed a Java N-IDE android application that was based on the Android SDK, Android NDK and JDK but did not wanted to run the application. Finds many errors in the underlying code so that it cannot create or use the application. I hope you're working on correcting mistakes.
> 
> Link to the application:
> 
> https://play.google.com/store/apps/details?id=com.duy.compiler.javanide

You need to build the whole source in Android Studio, read the instructions of what NDK or SDK and the other requirements it needs.
