### ISSUE TITLE
Cheat client

### ISSUE THREAD

**Issue by givemecheats** [longjunyu2/MCinaBox#331]
How can i run cheat client in mcinabox?

**Comment by xXTeraXx** [comment]
Why??

**Comment by givemecheats** [comment]
For fun

**Comment by Hacker1254** [comment]
How??
Its fun  for a few seconds than ruin 
> For fun

**Comment by TSaltedfishKing** [comment]
It can be implemented, but administrators will not let you do so if they customize the special client. You can only dream
