### ISSUE TITLE
又出现了 Android媒体扫描minecraft文件夹而引发的图库崩溃，急！求解决

### ISSUE THREAD

**Issue by yejunjie10311031** [longjunyu2/MCinaBox#333]
我在使用mcinabox0.1.3下载游戏版本时切了一下后台，再回来时整个软件就崩溃了，然后出现了使用mcinabox0.1.0时遇到的一样的问题，打开图库就无响应，qq里的图片无法查看，也无法截图。求解决办法。

**Comment by JohnsonLi06** [comment]
这个软件好像一切后台就闪退，貌似没法多开

**Comment by TSaltedfishKing** [comment]
是的,boat,mcinabox,bw都具有这个特性,

**Comment by TSaltedfishKing** [comment]
还在想办法(咕)
