### ISSUE TITLE
Please complite launcher configuration || Major Issue.

### ISSUE THREAD

**Issue by JustM1les** [longjunyu2/MCinaBox#338]
I'm installed _Minecraft 1.12.2_ and runtime _aarch32_runtime_20200328_.

When I'm try to start game - application says: "_Please complite launcher configuration_". So, I'm tried to reinstall runtime two times - nothing changed. Tried to reinstall Minecraft 1.12.2 - same. Nothing. Tried to reinstall whole application. And guess what? Nothing happend.

Technical information:
**Phone**: Samsung Galaxy A51.
**RAM**: 6 GB (3 GB free)
**OS**: Android 10.
**Version of MCinaBox**: 0.1.3.
**Allocated memory for Minecraft**: 768 MB.

**Photos**:
_Error message_:
![Screenshot_20200821-015457_MCinaBox](https://user-images.githubusercontent.com/69990794/90825846-f2e2e180-e352-11ea-9c4f-43550b3e0cd0.png)

_Lanuncher configuration_:
![Screenshot_20200821-021122_MCinaBox](https://user-images.githubusercontent.com/69990794/90826336-b5cb1f00-e353-11ea-9bd3-9b41242278b7.png)

_Global settings // Allocated memory for Minecraft_:
![Screenshot_20200821-021146_MCinaBox](https://user-images.githubusercontent.com/69990794/90826394-cda2a300-e353-11ea-8b11-1153cd04897b.png)

_Runtime screen_:
![Screenshot_20200821-021132_MCinaBox](https://user-images.githubusercontent.com/69990794/90826421-d7c4a180-e353-11ea-9cba-efa5d4329e2e.png)

**Comment by Hacker1254** [comment]
click this 
![image](https://user-images.githubusercontent.com/69991448/90827229-825fa480-e301-11ea-8b67-3973f25c7f0a.png)

**Comment by JustM1les** [comment]
I'm clicked this and says: "_Not create keyboard layout"_.

But, there's one more thing. When I'm try to load layout - app just crashes.
![Screenshot_20200821-022853_MCinaBox](https://user-images.githubusercontent.com/69990794/90827769-41de4600-e356-11ea-8091-bd9dda1b8fce.png)

**Comment by JustM1les** [comment]
Oh. I'm fixed this problem.

I'm created keyboard layout and Minecraft launched. Thanks, @Hacker1254.
