### ISSUE TITLE
Forge crashes on boot 

### ISSUE THREAD

**Issue by Jokkaj** [longjunyu2/MCinaBox#34]
(Android 10 / snapdragon 855) 
![Screenshot_2020-04-09-19-15-52-546_com miui bugreport~2](https://user-images.githubusercontent.com/58168823/78923041-de830400-7a97-11ea-83e0-06d82a4fdd37.jpg)

I installed forge 1.12.2 on my PC then I moved the forge version inside the versions folder in my phone, then I copied the Libraries folder fron my pc to my phone and created a config folder inside .minecraft (in my phone) where I created the splash.properties with enabled=false inside.
I can select forge from the launcher but it crashes on boot, am I forgetting something?
The app gives this error ...

**Comment by gabbosta** [comment]
how to install forge on mcinabox without PC? if so how

**Comment by Jokkaj** [comment]
> how to install forge on mcinabox without PC? if so how

You can't install it without pc for now

**Comment by miguelmazetto** [comment]
@longjunyu2 You never defined versionSettingS on ReadyToStart.java

**Comment by longjunyu2** [comment]
@miguelmazetto QAQ.Thank you for reminding me of bad programming
