### ISSUE TITLE
使用字体较细时看不清语言列表    can not see the language list with a finer font 

### ISSUE THREAD

**Issue by JohnsonLi06** [longjunyu2/MCinaBox#345]
建议加一个白色背景
A white background is recommended
![50d8ed90336ca8e67d0532e13aacb4f](https://user-images.githubusercontent.com/69753081/91013624-8994f400-e61a-11ea-85c2-be7317e15f99.jpg)

**Comment by JohnsonLi06** [comment]
emmm，最好解决亿下

**Comment by TSaltedfishKing** [comment]
自己可以改的

**Comment by TSaltedfishKing** [comment]
wiki里面有qq群，加一下，群里的人会教你的

**Comment by JohnsonLi06** [comment]
谢
