### ISSUE TITLE
Install forge lost the main jar flies

### ISSUE THREAD

**Issue by jiajia229** [longjunyu2/MCinaBox#347]
I could't install any forge.
The forge lost 1.7.10.jar,so I cannot use it.
I can download forge  computer but all versions are'nt working.
At last,I'm Chinese.
请问作者是中国人吗？😀😁

**Comment by TSaltedfishKing** [comment]
yep

**Comment by TSaltedfishKing** [comment]
请看置顶

**Comment by TSaltedfishKing** [comment]
Please provide equipment details

**Comment by jiajia229** [comment]
我很抱歉。
我的设备型号：荣耀20i
系统：ANDROID10

**Comment by TSaltedfishKing** [comment]
10没用了
9可以
下虚拟大师
