### ISSUE TITLE
aarch64_runtime_20200328.tar.xz

### ISSUE THREAD

**Issue by LegacyGamerHD** [longjunyu2/MCinaBox#35]
were can i find it

**Comment by gabbosta** [comment]
@longjunyu2

**Comment by LegacyGamerHD** [comment]
@gabbosta dont ping him he is busy

**Comment by gabbosta** [comment]
send the forge files to Minecraft 1.12.2 please

**Comment by LegacyGamerHD** [comment]
@gabbosta stop asking you cant even if you can it woeld just crash

**Comment by longjunyu2** [comment]
1.This is the openjdk that will be used:
https://github.com/AdoptOpenJDK/openjdk-aarch64-jdk8u
We need to compile openjdk through Android NDK. Please refer to the documentation of jdk9mobile：
http://openjdk.java.net/projects/mobile/android.html
2.This is the lwjgl to be used:
https://github.com/CosineMath/lwjgl-boat
https://github.com/CosineMath/lwjgl3-boat
https://github.com/CosineMath/glfw-boat
3.This is the GL4ES and OpenAL:
https://github.com/ptitSeb/gl4es
https://github.com/kcat/openal-soft

We need to compile these projects to get the runtime of other architectures. These look like a lot, but at least they will work.

**Comment by LegacyGamerHD** [comment]
@longjunyu2  i dont think i can do That might be hard

**Comment by LegacyGamerHD** [comment]
I will try at least

**Comment by LegacyGamerHD** [comment]
@longjunyu2  soryy i cant get it working

**Comment by miguelmazetto** [comment]
@LegacyGamerHD https://github.com/longjunyu2/MCinaBox/issues/38#issuecomment-611895769

**Comment by gabbosta** [comment]
We want the aarch64 runtime, not aarch32

**Comment by LegacyGamerHD** [comment]
@miguelmazetto uhm yes i need 64 bit not 32 bit

**Comment by AyHa1810** [comment]
OpenJDK aarch64 binary -
[https://adoptopenjdk.net/releases.html](https://adoptopenjdk.net/releases.html) 
LWJGL - 
[https://github.com/CosineMath/lwjgl-boat](https://github.com/CosineMath/lwjgl-boat) 
[https://github.com/CosineMath/lwjgl3-boat](https://github.com/CosineMath/lwjgl3-boat) 
[https://github.com/CosineMath/glfw-boat](https://github.com/CosineMath/glfw-boat) 
GL4ES -
[https://github.com/ptitSeb/gl4es](https://github.com/ptitSeb/gl4es) 
OpeaAL -
[https://github.com/kcat/openal-soft](https://github.com/kcat/openal-soft) 

Please make aarch64 runtime pack with the given links.

**Comment by LegacyGamerHD** [comment]
> OpenJDK aarch64 binary -
> https://adoptopenjdk.net/releases.html
> LWJGL -
> https://github.com/CosineMath/lwjgl-boat
> https://github.com/CosineMath/lwjgl3-boat
> https://github.com/CosineMath/glfw-boat
> GL4ES -
> https://github.com/ptitSeb/gl4es
> OpeaAL -
> https://github.com/kcat/openal-soft
> 
> Please make aarch64 runtime pack with the given links.

Your Java link is for desktop also if I can I woeld of posted it already

**Comment by LegacyGamerHD** [comment]
@longjunyu2 can make that aarch64 runtime

**Comment by AyHa1810** [comment]
Ok fine, Source Code is Source Code. From one Source Code, we can build the program/app/binary for multiple platforms. So we need to build it from their source codes. 
Sorry but I can't build.

**Comment by AyHa1810** [comment]
> @longjunyu2 can make that aarch64 runtime

The java link is only binary for linux. When I checked the aarch32 runtime pack, I saw that the java (aarch32-runtime-20200320.tar.xz/j2re/) folder contains the aarch32 binary for linux. Although, Android is build on modified linux kernel.
But sorry, I don't know much about programming and linux. ;(
