### ISSUE TITLE
Important thing.

### ISSUE THREAD

**Issue by Malaska678** [longjunyu2/MCinaBox#356]
In last issue i created, I say that i modify that version.jar to install mods and i delete metainf.
Can we get a meta inf that we can put at optifine 1.15.2.jar so that it would work. :)

**Comment by Malaska678** [comment]
@TSaltedfishKing

**Comment by TSaltedfishKing** [comment]
emmmm

**Comment by Malaska678** [comment]
Can i get the new keta inf

**Comment by Malaska678** [comment]
*meta inf

**Comment by Malaska678** [comment]
Are you attempting to solve the issue

**Comment by KUALALUM** [comment]
> Can i get the new keta inf

Yes thats right

**Comment by Malaska678** [comment]
Why no one is responding :/
