### ISSUE TITLE
[BUG] Cannot install Forge 2854 or 2847

### ISSUE THREAD

**Issue by vico93** [longjunyu2/MCinaBox#368]
Device: Galaxy A8 (2018)
Android version: 9
RAM: 3.9GB
CPU: aarch64

Basically when i download both 2847 or 2854 (for 1.12.2) universal jars and place on the correct folder, when i touch install those kanjis appears. Dont know what it means. No Forge appears to play
![Screenshot_20200905-054117_MCinaBox](https://user-images.githubusercontent.com/3485505/92301537-10ab6b80-ef3b-11ea-9483-250aa00a99c7.jpg)

**Comment by Kotarou2k4** [comment]
Don't use official download source

**Comment by vico93** [comment]
@Kotarou2k4 what should i use?

**Comment by vico93** [comment]
Yeah selecting mcbbs and selecting the installer jars fixed my issue. Thanks!
