### ISSUE TITLE
emmm

### ISSUE THREAD

**Issue by CPXMC** [longjunyu2/MCinaBox#4]
选择一个版本会把所有资源重新下载一遍,无论当前是否有该资源，比如assets文件夹

**Comment by yejunjie10311031** [comment]
MCinabox，boat和boardwalk的资源都是相通的，你可以挂vpn去boardwalk上下载，然后把/0/boardwalk/gamedir重命名为. minecraft，移动到/0/MCinabox里。

**Comment by longjunyu2** [comment]
好的，我会尝试在下一个版本修复这个问题。

**Comment by CPXMC** [comment]
> 好的，我会尝试在下一个版本修复这个问题。

支持！

**Comment by CPXMC** [comment]
> MCinabox，boat和boardwalk的资源都是相通的，你可以挂vpn去boardwalk上下载，然后把/0/boardwalk/gamedir重命名为. minecraft，移动到/0/MCinabox里。

这个我知道
