### ISSUE TITLE
希望添加的新功能

### ISSUE THREAD

**Issue by CPXMC** [longjunyu2/MCinaBox#40]
按键编辑按钮的背景，最好可以让玩家自定义

**Comment by CosineMath** [comment]
很抱歉没有理解你的意思，请详细描述一下。

**Comment by CPXMC** [comment]
> 很抱歉没有理解你的意思，请详细描述一下。

就是编辑按键的界面的背景，可以让玩家自定义。

**Comment by longjunyu2** [comment]
你的意思是按键背景自定义还是说界面背景自定义？

**Comment by longjunyu2** [comment]
计划编辑功能将会支持Minecraft界面内编辑。

**Comment by CPXMC** [comment]
> 你的意思是按键背景自定义还是说界面背景自定义？

界面

**Comment by CPXMC** [comment]
> 计划编辑功能将会支持Minecraft接口内部编辑。

希望添加个自定义游戏路径的功能

**Comment by longjunyu2** [comment]
好的
