### ISSUE TITLE
I got forge working!

### ISSUE THREAD

**Issue by miguelmazetto** [longjunyu2/MCinaBox#41]
![Screenshot_20200410-114534](https://user-images.githubusercontent.com/33629994/78999488-1f732b00-7b21-11ea-87ac-1c45e51979f8.png)
So, i did change some stuff on ReadyToStart.java, i'll try to do the pull request,idk really know how to do this correctly.
It seems like even after the latest commit there was a thing that still wasn't right, it was trying to load the forge file as main jar and minecraft as additional,so i just switched.

**Comment by miguelmazetto** [comment]
I also tested liteloader it works just fine,but there is still a case where this still will not work,when you have the combination liteloader+forge,that you have a liteloader.json that inherits a forge.json that inherits minecraft.json

**Comment by gabbosta** [comment]
please send these forge files to Minecraft 1.12.2, I really want the forge

**Comment by Jokkaj** [comment]
> 
> 
> ![Screenshot_20200410-114534](https://user-images.githubusercontent.com/33629994/78999488-1f732b00-7b21-11ea-87ac-1c45e51979f8.png)
> So, i did change some stuff on ReadyToStart.java, i'll try to do the pull request,idk really know how to do this correctly.
> It seems like even after the latest commit there was a thing that still wasn't right, it was trying to load the forge file as main jar and minecraft as additional,so i just switched.

what file did you switch? the forge .json file? my forge folder inside versions doesn't have a "forge.jar" file, only a json, could you send your versions folder?

**Comment by miguelmazetto** [comment]
> > ![Screenshot_20200410-114534](https://user-images.githubusercontent.com/33629994/78999488-1f732b00-7b21-11ea-87ac-1c45e51979f8.png)
> > So, i did change some stuff on ReadyToStart.java, i'll try to do the pull request,idk really know how to do this correctly.
> > It seems like even after the latest commit there was a thing that still wasn't right, it was trying to load the forge file as main jar and minecraft as additional,so i just switched.
> 
> what file did you switch? the forge .json file? my forge folder inside versions doesn't have a "forge.jar" file, only a json, could you send your versions folder?

no i actually had to change some files in the source code
