### ISSUE TITLE
How Get runtime file 

### ISSUE THREAD

**Issue by XIDigbyKun** [longjunyu2/MCinaBox#50]
Hello,
I need help how to get runtime file

**Comment by LegacyGamerHD** [comment]
https://github.com/longjunyu2/MCinaBox/releases/download/v0.1.0/aarch32_runtime_20200328.tar.xz

**Comment by LegacyGamerHD** [comment]
look at release tracker first before asking qeastions

**Comment by XIDigbyKun** [comment]
Ok

**Comment by XIDigbyKun** [comment]
Thank for info
