### ISSUE TITLE
"Please complete the configuration for launcher"

### ISSUE THREAD

**Issue by ShiromcID** [longjunyu2/MCinaBox#51]
I don't know when I started the McinaBox launcher I had this problem

![Screenshot_2020-04-13-02-06-24-72](https://user-images.githubusercontent.com/63558829/79077422-dfcc5f00-7d2b-11ea-9a97-3fb24af84926.png)

**Comment by szarik001** [comment]
Tap the red circle in the top right to show what you have to configure

**Comment by ShiromcID** [comment]
"Local runtime is not installed"

where should I get a runtime

**Comment by ayunami2000** [comment]
Its under the first release of the APK on github

**Comment by LegacyGamerHD** [comment]
https://github.com/longjunyu2/MCinaBox/releases/download/v0.1.0/aarch32_runtime_20200328.tar.xz

**Comment by ShiromcID** [comment]
/sdcard/android/data/com.aof.mcinabox/files/McinaBox/runtimepack

I've put aarch32_runtime_20200328 in the runtime folder folder and I have installed it on mcinabox but still can't
