### ISSUE TITLE
keyboard layout ?

### ISSUE THREAD

**Issue by J0SH1X** [longjunyu2/MCinaBox#54]
can anyone upload his keyboardlayout , i cant seem to get it to work

**Comment by Jokkaj** [comment]
> can anyone upload his keyboardlayout , i cant seem to get it to work
[test.zip](https://github.com/longjunyu2/MCinaBox/files/4472318/test.zip)

**Comment by longjunyu2** [comment]
Keyboard layout is not universal when the screen size of mobile phone is different. It's better to make it by yourself.
