### ISSUE TITLE
远古版无法启动

### ISSUE THREAD

**Issue by yejunjie10311031** [longjunyu2/MCinaBox#6]

**Comment by longjunyu2** [comment]
远古版，需求比较少，资料也很少。如果可以的话提供一下崩溃时的日志。包括:boat_output.txt和crash-reports

**Comment by CPXMC** [comment]
> 远古版，需求比较少，资料也很少。如果可以的话提供一下崩溃时的日志。包括:boat_output.txt和crash-reports

我给你日志，你能帮我解答一下吗？

**Comment by CPXMC** [comment]
> 远古版，需求比较少，资料也很少。如果可以的话提供一下崩溃时的日志。包括:boat_output.txt和crash-reports

[boat_output.txt](https://github.com/longjunyu2/MCinaBox/files/4415108/boat_output.txt)
