### ISSUE TITLE
is it possible to play on servers

### ISSUE THREAD

**Issue by idscic** [longjunyu2/MCinaBox#60]
using a premium account and the server is online mode

**Comment by LegacyGamerHD** [comment]
yes it is

**Comment by LegacyGamerHD** [comment]
do it lags like madman for me

**Comment by idscic** [comment]
how

> do it lags like madman for me

**Comment by idscic** [comment]
> do it lags like madman for me

how do i do it

**Comment by idscic** [comment]
@LegacyGamerHD do you have a guide on it

**Comment by LegacyGamerHD** [comment]
us this apk
[mcinabox-release.zip](https://github.com/longjunyu2/MCinaBox/files/4474765/mcinabox-release.zip) latest non released version

**Comment by LegacyGamerHD** [comment]
strait from source code
