### ISSUE TITLE
Can't download older releases

### ISSUE THREAD

**Issue by szarik001** [longjunyu2/MCinaBox#62]
When downloading from releases on GitHub, only the most recent one works (v0.1.3). This also means I cannot download the required aarch32_runtime.

**Comment by ayunami2000** [comment]
The runtime is in the same releases thing, not with the apk. Check the files under the first release, there's a .tar.xz file there too.

**Comment by szarik001** [comment]
I can't download anything apart from the newest release. That includes the aarch32 runtime from the first one.

**Comment by ayunami2000** [comment]
Click on assets under the release and you will see the files. I have
provided the direct link to it as well.
https://github.com/longjunyu2/MCinaBox/releases/download/v0.1.0/aarch32_runtime_20200328.tar.xz
