### ISSUE TITLE
can you put a resource pack?

### ISSUE THREAD

**Issue by joaquinleiva** [longjunyu2/MCinaBox#63]
can you put a resource pack?

**Comment by szarik001** [comment]
Try placing your resourcepack.zip in the /MCinaBox/.minecraft/resourcepacks folder. You should then be able to select it from the game settings

**Comment by joaquinleiva** [comment]
> Intente colocar su resourcepack.zip en la carpeta /MCinaBox/.minecraft/resourcepacks. Entonces deberías poder seleccionarlo desde la configuración del juego

I have the MCinaBox folder but I don't have the folder that says Minecraft

**Comment by szarik001** [comment]
The .minecraft folder on your device might be hidden. Try changing your file manager settings to show hidden files and folders or download a different file manager.

**Comment by joaquinleiva** [comment]
thanks it was because the folder was hidden

**Comment by joaquinleiva** [comment]
One last question, how can I install OptiFine?

**Comment by szarik001** [comment]
Not sure if it will work but you can try to install it on a computer then move the files over to your phone. I haven't tried this so I don't know if this will work.

**Comment by joaquinleiva** [comment]
> No estoy seguro de si funcionará, pero puede intentar instalarlo en una computadora y luego mover los archivos a su teléfono. No he probado esto, así que no sé si funcionará.

If I had a computer I would not be downloading Minecraft from Java on Android

**Comment by joaquinleiva** [comment]
> > No estoy seguro de si funcionará, pero puedo intentar instalarlo en una computadora y luego mover los archivos a su teléfono. No he probado esto, así que no sé si funcionará.
> 
> Si tuviera una computadora, no estaría descargando Minecraft de Java en Android

if it works could you pass me the files
