### ISSUE TITLE
Ticking entity错误崩溃

### ISSUE THREAD

**Issue by yejunjie10311031** [longjunyu2/MCinaBox#7]
boat玩1.8.9～1.12.2有时玩着玩着会突然崩溃，错误描述为ticking entity，forge版可以在forge. cfg中修复这种错误，但是MCinabox不能运行forge版，要怎么避免这种类型的崩溃？

**Comment by longjunyu2** [comment]
mcinabox可以运行forge。自行解决。

**Comment by yejunjie10311031** [comment]
forge版不能运行啊，我用boat可用的forge版移到MCinabox中去会启动闪退

**Comment by longjunyu2** [comment]
我在看一看

**Comment by longjunyu2** [comment]
已经实现mod，请参照文档进行修改！
