### ISSUE TITLE
Downloading resources of minecraft stucking in 98%

### ISSUE THREAD

**Issue by alekseiytalanov** [longjunyu2/MCinaBox#70]
I am trying to install minecraft but downloading resources is stucking in 98%

My device:
DEXP Ursus N370
Android 8.1.0 Oreo go
1 gb ram
16 gb rom

**Comment by by-scott** [comment]
这是未知bug导致的，你可以取消下载，然后再重新下载，可以正常游戏。

**Comment by alekseiytalanov** [comment]
> 这是未知bug导致的，你可以取消下载，然后再重新下载，可以正常游戏。

Please translate i don't understand

**Comment by by-scott** [comment]
1、Cancel Download
↓↓↓↓↓↓↓↓↓
2、Download again
