### ISSUE TITLE
V0.1.3

### ISSUE THREAD

**Issue by AyHa1810** [longjunyu2/MCinaBox#72]
Please release the v0.1.3 apk. :)

**Comment by littlefunny233** [comment]
It's easy to build the apk on AndroidStudio by ownself

**Comment by LegacyGamerHD** [comment]
its already out

**Comment by AyHa1810** [comment]
> It's easy to build the apk on AndroidStudio by ownself

My pc definitely sucks! It's so slow that I want to blow it up with billions of TNTs!
This thingy is even not made for some basic programs.

**Comment by AyHa1810** [comment]
> its already out

I can't see the apk. Only 2 different archives of same source code.

**Comment by idscic** [comment]
if someone gets an apk @ me

**Comment by by-scott** [comment]
新版本已经发布了，请浏览https://github.com/longjunyu2/MCinaBox/releases
