### ISSUE TITLE
you can install forge and OptiFine?

### ISSUE THREAD

**Issue by joaquinleiva** [longjunyu2/MCinaBox#77]
you can install forge and OptiFine?

**Comment by by-scott** [comment]
新版本已经可以安装forge了。
https://github.com/longjunyu2/MCinaBox/releases

**Comment by 18296565196** [comment]
The new version is ready to install forge.

**Comment by LegacyGamerHD** [comment]
@18296565196  @by-scott  whats diffrent then the prerelease

**Comment by by-scott** [comment]
> @ 18296565196 @ by-scott 与预发行版有何不同



> @18296565196 @by-scott whats diffrent then the prerelease

1、Open forge installation
2、Eliminate accidental exits

**Comment by LegacyGamerHD** [comment]
> > @ 18296565196 @ by-scott 与预发行版有何不同
> 
> > @18296565196 @by-scott whats diffrent then the prerelease
> 
> 1、Open forge installation in settings
> 2、Eliminate accidental exits

i dident ask for that

**Comment by alekseiytalanov** [comment]
> > @ 18296565196 @ by-scott 与预发行版有何不同
> 
> > @18296565196 @by-scott whats diffrent then the prerelease
> 
> 1、Open forge installation in settings
> 2、Eliminate accidental exits

What forge installation? In launcher settings and anywhere not exists Open forge installation

**Comment by by-scott** [comment]
> > > @ 18296565196 @ by-scott 与预发行版有何不同
> > 
> > 
> > > @18296565196 @by-scott whats diffrent then the prerelease
> > 
> > 
> > 1、Open forge installation in settings
> > 2、Eliminate accidental exits
> 
> What forge installation? In launcher settings and anywhere not exists Open forge installation

![Screenshot_2020-04-16-19-24-00-754_com aof mcinabox](https://user-images.githubusercontent.com/63074534/79450726-dd158680-8017-11ea-8d5d-25dc38b7521c.jpg)
Forge Installer.

**Comment by by-scott** [comment]
> > > @ 18296565196 @ by-scott 与预发行版有何不同
> > 
> > 
> > > @18296565196 @by-scott whats diffrent then the prerelease
> > 
> > 
> > 1、Open forge installation in settings
> > 2、Eliminate accidental exits
> 
> What forge installation? In launcher settings and anywhere not exists Open forge installation

version 0.1.3 has been republished. Please download and install again.
