### ISSUE TITLE
How to install Forge?

### ISSUE THREAD

**Issue by alekseiytalanov** [longjunyu2/MCinaBox#81]
Folder forgeinstaller in shared app data in /sdcard/android/"App package name"/ exists but this can't interact with launcher How to install Forge using this folder?

**Comment by by-scott** [comment]
Please download ：forge-xxx-universal
Place it in the forgeinstaller directory

**Comment by Owningle** [comment]
> Please download ：forge-xxx-universal.jar
> Place it in the forgeinstaller directory
> Open settings, use forge installer
> If the forge installer does not exist, Download 0.1.3 again, which has been republished today.

I tried doing this, but when i click install, the app crashes. I tried using forge-xxx-installer.jar earlier, it worked, but got to 90% and then kept saying download failed.

**Comment by by-scott** [comment]
Game version 1.15.2 Use forge-xxx-installer.jar
Game version 1.12.2 and earlier Use forge-xxx-universal.jar
If the download fails, it is a network problem, please download again

**Comment by by-scott** [comment]
> > Please download ：forge-xxx-universal.jar
> > Place it in the forgeinstaller directory
> > Open settings, use forge installer
> > If the forge installer does not exist, Download 0.1.3 again, which has been republished today.
> 
> I tried doing this, but when i click install, the app crashes. I tried using forge-xxx-installer.jar earlier, it worked, but got to 90% and then kept saying download failed.
> 
> Edit: trying to install for 1.15.2 to install optiforge to get optifine, not sure if this is an issue.

Game version 1.15.2 Use forge-xxx-installer.jar
Game version 1.12.2 and earlier Use forge-xxx-universal.jar
If the download fails, it is a network problem, please download again

**Comment by Owningle** [comment]
> > > Please download ：forge-xxx-universal.jar
> > > Place it in the forgeinstaller directory
> > > Open settings, use forge installer
> > > If the forge installer does not exist, Download 0.1.3 again, which has been republished today.
> > 
> > 
> > I tried doing this, but when i click install, the app crashes. I tried using forge-xxx-installer.jar earlier, it worked, but got to 90% and then kept saying download failed.
> > Edit: trying to install for 1.15.2 to install optiforge to get optifine, not sure if this is an issue.
> 
> Game version 1.15.2 Use forge-xxx-installer.jar
> Game version 1.12.2 and earlier Use forge-xxx-universal.jar
> If the download fails, it is a network problem, please download again

I have tried reinstalling the app, and starting the download again, but it still says download failed at about 70%, it is fine up until then, but will not progress past that, even when trying to download again, just stays on 70% and then fails.

**Comment by alekseiytalanov** [comment]
Forge can't install i press install after pasting forge universal jar and forge installer jar after pressing install kept says me in Chinese i don't understand Chinese and nothing

**Comment by Owningle** [comment]
> Forge can't install i press install after pasting forge universal jar and forge installer jar after pressing install kept says me in Chinese i don't understand Chinese and nothing

try changing download source, at the top, default is official

**Comment by by-scott** [comment]
> Forge can't install i press install after pasting forge universal jar and forge installer jar after pressing install kept says me in Chinese i don't understand Chinese and nothing

Download source needs to be replaced

**Comment by by-scott** [comment]
> > > > Please download ：forge-xxx-universal.jar
> > > > Place it in the forgeinstaller directory
> > > > Open settings, use forge installer
> > > > If the forge installer does not exist, Download 0.1.3 again, which has been republished today.
> > > 
> > > 
> > > I tried doing this, but when i click install, the app crashes. I tried using forge-xxx-installer.jar earlier, it worked, but got to 90% and then kept saying download failed.
> > > Edit: trying to install for 1.15.2 to install optiforge to get optifine, not sure if this is an issue.
> > 
> > 
> > Game version 1.15.2 Use forge-xxx-installer.jar
> > Game version 1.12.2 and earlier Use forge-xxx-universal.jar
> > If the download fails, it is a network problem, please download again
> 
> I have tried reinstalling the app, and starting the download again, but it still says download failed at about 70%, it is fine up until then, but will not progress past that, even when trying to download again, just stays on 70% and then fails.

I guess the download source server may cause you to download slowly in China

**Comment by by-scott** [comment]
Because I use Google translation, the expression may not be accurate

**Comment by Owningle** [comment]
> Because I use Google translation, the expression may be accurate not

It's okay, i understand, would it be better for me to use the old method for now?

**Comment by by-scott** [comment]
> > Because I use Google translation, the expression may be accurate not
> 
> It's okay, i understand, would it be better for me to use the old method for now?

Yes, if the new method still doesn't work

**Comment by Owningle** [comment]
> > > Because I use Google translation, the expression may be accurate not
> > 
> > 
> > It's okay, i understand, would it be better for me to use the old method for now?
> 
> Yes, if the new method still doesn't work

Have gone ahead and tried the old method, however, when trying to start the game, it app instantly crashes.

**Comment by by-scott** [comment]
> > > > Because I use Google translation, the expression may be accurate not
> > > 
> > > 
> > > It's okay, i understand, would it be better for me to use the old method for now?
> > 
> > 
> > Yes, if the new method still doesn't work
> 
> Have gone ahead and tried the old method, however, when trying to start the game, it app instantly crashes.

Modify file ：/storage/emulated/0/MCinaBox/.minecraft/config/splash.properties
enabled=false

**Comment by by-scott** [comment]
> > > > Because I use Google translation, the expression may be accurate not
> > > 
> > > 
> > > It's okay, i understand, would it be better for me to use the old method for now?
> > 
> > 
> > Yes, if the new method still doesn't work
> 
> Have gone ahead and tried the old method, however, when trying to start the game, it app instantly crashes.

The folder(.minecraft) may be hidden. You try to open show hidden files in your file manager

**Comment by Owningle** [comment]
> > > > > Because I use Google translation, the expression may be accurate not
> > > > 
> > > > 
> > > > It's okay, i understand, would it be better for me to use the old method for now?
> > > 
> > > 
> > > Yes, if the new method still doesn't work
> > 
> > 
> > Have gone ahead and tried the old method, however, when trying to start the game, it app instantly crashes.
> 
> Modify file ：MCinaBox/.minecraft/config/splash.properties
> enabled=false

No config folder exists, only folders there are saves, libraries, assets, crash-reports, resourcepacks, and versions

**Comment by by-scott** [comment]
> > > > > > Because I use Google translation, the expression may be accurate not
> > > > > 
> > > > > 
> > > > > It's okay, i understand, would it be better for me to use the old method for now?
> > > > 
> > > > 
> > > > Yes, if the new method still doesn't work
> > > 
> > > 
> > > Have gone ahead and tried the old method, however, when trying to start the game, it app instantly crashes.
> > 
> > 
> > Modify file ：MCinaBox/.minecraft/config/splash.properties
> > enabled=false
> 
> No config folder exists, only folders there are saves, libraries, assets, crash-reports, resourcepacks, and versions

your old way  may be different from what I thought
I want to know how you installed Forge

**Comment by Owningle** [comment]
> > > > > > > Because I use Google translation, the expression may be accurate not
> > > > > > 
> > > > > > 
> > > > > > It's okay, i understand, would it be better for me to use the old method for now?
> > > > > 
> > > > > 
> > > > > Yes, if the new method still doesn't work
> > > > 
> > > > 
> > > > Have gone ahead and tried the old method, however, when trying to start the game, it app instantly crashes.
> > > 
> > > 
> > > Modify file ：MCinaBox/.minecraft/config/splash.properties
> > > enabled=false
> > 
> > 
> > No config folder exists, only folders there are saves, libraries, assets, crash-reports, resourcepacks, and versions
> 
> your old way may be different from what I thought.
> I want to know how you installed Forge.

This is what i did:

1. install forge on pc
2. ran forge on pc to ensure it is working
3. moved folders from .minecraft on pc to the .minecraft folder in internal storage/mcinabox
4. tried to run game
5. went to change the splash.properties file, but there is no config folder in the .minecraft folder.


vanilla 1.15.2 runs fine.

**Comment by by-scott** [comment]
> > > > > > > > Because I use Google translation, the expression may be accurate not
> > > > > > > 
> > > > > > > 
> > > > > > > It's okay, i understand, would it be better for me to use the old method for now?
> > > > > > 
> > > > > > 
> > > > > > Yes, if the new method still doesn't work
> > > > > 
> > > > > 
> > > > > Have gone ahead and tried the old method, however, when trying to start the game, it app instantly crashes.
> > > > 
> > > > 
> > > > Modify file ：MCinaBox/.minecraft/config/splash.properties
> > > > enabled=false
> > > 
> > > 
> > > No config folder exists, only folders there are saves, libraries, assets, crash-reports, resourcepacks, and versions
> > 
> > 
> > your old way may be different from what I thought.
> > I want to know how you installed Forge.
> 
> This is what i did:
> 
> 1. install forge on pc
> 2. ran forge on pc to ensure it is working
> 3. moved folders from .minecraft on pc to the .minecraft folder in internal storage/mcinabox
> 4. tried to run game
> 5. went to change the splash.properties file, but there is no config folder in the .minecraft folder.
> 
> vanilla 1.15.2 runs fine.

I'll try. Just a moment, please

**Comment by Owningle** [comment]
> > > > > > > > > Because I use Google translation, the expression may be accurate not
> > > > > > > > 
> > > > > > > > 
> > > > > > > > It's okay, i understand, would it be better for me to use the old method for now?
> > > > > > > 
> > > > > > > 
> > > > > > > Yes, if the new method still doesn't work
> > > > > > 
> > > > > > 
> > > > > > Have gone ahead and tried the old method, however, when trying to start the game, it app instantly crashes.
> > > > > 
> > > > > 
> > > > > Modify file ：MCinaBox/.minecraft/config/splash.properties
> > > > > enabled=false
> > > > 
> > > > 
> > > > No config folder exists, only folders there are saves, libraries, assets, crash-reports, resourcepacks, and versions
> > > 
> > > 
> > > your old way may be different from what I thought.
> > > I want to know how you installed Forge.
> > 
> > 
> > This is what i did:
> > 
> > 1. install forge on pc
> > 2. ran forge on pc to ensure it is working
> > 3. moved folders from .minecraft on pc to the .minecraft folder in internal storage/mcinabox
> > 4. tried to run game
> > 5. went to change the splash.properties file, but there is no config folder in the .minecraft folder.
> > 
> > vanilla 1.15.2 runs fine.
> 
> I'll try. Just a moment, please

Just want to add that i am using the latest forge build, 1.15.2 - 31.1.46

**Comment by by-scott** [comment]
> > > > > > > > > > Because I use Google translation, the expression may be accurate not
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > It's okay, i understand, would it be better for me to use the old method for now?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Yes, if the new method still doesn't work
> > > > > > > 
> > > > > > > 
> > > > > > > Have gone ahead and tried the old method, however, when trying to start the game, it app instantly crashes.
> > > > > > 
> > > > > > 
> > > > > > Modify file ：MCinaBox/.minecraft/config/splash.properties
> > > > > > enabled=false
> > > > > 
> > > > > 
> > > > > No config folder exists, only folders there are saves, libraries, assets, crash-reports, resourcepacks, and versions
> > > > 
> > > > 
> > > > your old way may be different from what I thought.
> > > > I want to know how you installed Forge.
> > > 
> > > 
> > > This is what i did:
> > > 
> > > 1. install forge on pc
> > > 2. ran forge on pc to ensure it is working
> > > 3. moved folders from .minecraft on pc to the .minecraft folder in internal storage/mcinabox
> > > 4. tried to run game
> > > 5. went to change the splash.properties file, but there is no config folder in the .minecraft folder.
> > > 
> > > vanilla 1.15.2 runs fine.
> > 
> > 
> > I'll try. Just a moment, please
> 
> Just want to add that i am using the latest forge build, 1.15.2 - 31.1.46

I failed. you can use this method in the version 0.1.2？
Game version 1.12.2 can be used normally. It is recommended that you use it

**Comment by by-scott** [comment]
@Owningle I think we should use@，Because it's too long

**Comment by Jokkaj** [comment]
> 
> 
> > > > > > > > Because I use Google translation, the expression may be accurate not
> > > > > > > 
> > > > > > > 
> > > > > > > It's okay, i understand, would it be better for me to use the old method for now?
> > > > > > 
> > > > > > 
> > > > > > Yes, if the new method still doesn't work
> > > > > 
> > > > > 
> > > > > Have gone ahead and tried the old method, however, when trying to start the game, it app instantly crashes.
> > > > 
> > > > 
> > > > Modify file ：MCinaBox/.minecraft/config/splash.properties
> > > > enabled=false
> > > 
> > > 
> > > No config folder exists, only folders there are saves, libraries, assets, crash-reports, resourcepacks, and versions
> > 
> > 
> > your old way may be different from what I thought.
> > I want to know how you installed Forge.
> 
> This is what i did:
> 
>     1. install forge on pc
> 
>     2. ran forge on pc to ensure it is working
> 
>     3. moved folders from .minecraft on pc to the .minecraft folder in internal storage/mcinabox
> 
>     4. tried to run game
> 
>     5. went to change the splash.properties file, but there is no config folder in the .minecraft folder.
> 
> 
> vanilla 1.15.2 runs fine.

I used the old method too (1.12.2) and it worked! try to start from a clean .minecraft folder on pc (move away from roaming your older .minecraft folder), you should have a "config" folder with splash.properties, I'm sending you my folder here (already pre-configged)
[forge configs.zip](https://github.com/longjunyu2/MCinaBox/files/4487553/forge.configs.zip)
.
Also, how did you get vanilla 1.15.2 to work ? I can't play that version, It's all glitchy even with mipmap off.
