### ISSUE TITLE
1.15.x Rendering Issues

### ISSUE THREAD

**Issue by AyHa1810** [longjunyu2/MCinaBox#83]
![Screenshot_2020-04-16-18-41-48-40_4cb6582af5c3b01ac644d295dc92f43e](https://user-images.githubusercontent.com/63386848/79460310-42ff0f80-8012-11ea-812a-01b79cbc8670.png)
The launcher cannot render the chunks perfectly. Please fix this. :)

I think this is a problem with OpenGL or GL4ES.

**Comment by LegacyGamerHD** [comment]
dublicated with #24

**Comment by AyHa1810** [comment]
> dublicated with #24

But I experienced this myself!

**Comment by LegacyGamerHD** [comment]
@AyHa1810 there is a issue already open for it
