### ISSUE TITLE
Latest release - only a few premium servers let me connect

### ISSUE THREAD

**Issue by Jokkaj** [longjunyu2/MCinaBox#85]
Server such as hypixel of cubecraft give off "io.netty.channel.ConnectTimeoutException: Connection timed out:" errors and their MOTD won't display.
using vanilla 1.12.2 (the latest playable version)

**Comment by LegacyGamerHD** [comment]
True I can confirm this

**Comment by diamond-gold** [comment]
It is working fine for me
![Screenshot_20200417_114818_com aof mcinabox](https://user-images.githubusercontent.com/10301312/79530317-94a2ab00-80a1-11ea-9b52-3f9c3dccfbf0.jpg)
![Screenshot_20200417_114908_com aof mcinabox](https://user-images.githubusercontent.com/10301312/79530327-99675f00-80a1-11ea-80b8-e6b896b0c9cb.jpg)

**Comment by ShiromcID** [comment]
Try to connect with your premium server's IP address. Don't sub-subdomain will not be connected

**Comment by Jokkaj** [comment]
> Try to connect with your premium server's IP address. Don't sub-subdomain will not be connected

Using the full ip will fix the issue (for hypixel it's mc.hypixel.net and for cubecraft it's play.cubecraft.net)

**Comment by gabbosta** [comment]
I'm trying to log in to servers but when I log in it appears that my account is invalid, but I don't have a computer Minecraft account, how do I do it?

**Comment by Jokkaj** [comment]
> I'm trying to log in to servers but when I log in it appears that my account is invalid, but I don't have a computer Minecraft account, how do I do it?

Buy a minecraft pc account here
https://www.minecraft.net/it-it/
Or just play on SP servers (servers for who don't have premium minecraft).
You can't play on premium servers like hypixel without a premium account.
