### ISSUE TITLE
force close when start the game

### ISSUE THREAD

**Issue by ShiromcID** [longjunyu2/MCinaBox#86]
![Screenshot_2020-04-17-01-59-49-23-picsay](https://user-images.githubusercontent.com/63558829/79496461-5d57de00-8050-11ea-9696-9ff578bf3461.png)

I have installed the game version until it's finished but when I started the game suddenly force close

**Comment by diamond-gold** [comment]
Did you set the max memory above 1000mb? i have tested 1000 is the max, anything higher will crash. Also you should update to v0.1.3

**Comment by longjunyu2** [comment]
Please check your Memory setting.

**Comment by ShiromcID** [comment]
McinaBox v 0.1.3 can't installed
