### ISSUE TITLE
Mcinabox0.1.3 can't be installed.

### ISSUE THREAD

**Issue by lizeyan200711** [longjunyu2/MCinaBox#87]
Mcinabox0.1.3 can't be installed. My installation prompt: the application is not installed, but 0.1.0-0.1.2 can be installed. Do you know?

I'd like to help you develop as much as I can. I want to make the notes English, but I won't get rid of Chinese, but I don't have permission. Do you agree? >

**Comment by longjunyu2** [comment]
会说中国话用汉语，谢谢，需要更多资料

**Comment by lizeyan200711** [comment]
无法安装Mcinabox0.1.3。我的安装提示：应用程序未安装，但可以安装0.1.0-0.1.2

**Comment by lizeyan200711** [comment]
Mcinabox0.1.3的第一次发布可以安装并启动，但现在这版本无法成功安装，即使我删除重新安装，它也提示：应用程序未安装

**Comment by ShiromcID** [comment]
You can use the "APK editor" application to install it

You can install the APK Editor in the Play store
