### ISSUE TITLE
Cant type text using keyboard.

### ISSUE THREAD

**Issue by leetmussc** [longjunyu2/MCinaBox#88]
The keyboard in this app is basically unusable for typing text.i cant add servers.

**Comment by Jokkaj** [comment]
> The keyboard in this app is basically unusable for typing text.i cant add servers.

True, only the space, alt , control and start buttons work

**Comment by longjunyu2** [comment]
No, you wrong.You can easily type words by enable a switch like ```<>``` on the toolbar in MCinaBox.Then click the textview which occureed on the top-right of the screen.You will be able to type word by system keyboard instead of keyboard in MCinaBox.

**Comment by longjunyu2** [comment]
The keyboard in MCinaBox can only control minecraft not type words.Although I think this is complex to use, there is no method to change it easily :)

**Comment by leetmussc** [comment]
Thank you
