### ISSUE TITLE
无法安装Mcinabox0.1.3。

### ISSUE THREAD

**Issue by lizeyan200711** [longjunyu2/MCinaBox#90]
无法安装Mcinabox0.1.3。我的安装提示：应用程序未安装，但可以安装0.1.0-0.1.2。你知道吗？

我想尽我所能帮助MCinaBox发展。我想把笔记写成英文，但我不会去掉中文，但我没有得到许可。同意吗？>

**Comment by longjunyu2** [comment]
能说一下安卓版本吗?

**Comment by longjunyu2** [comment]
有一些系统的安装包程序会阻止相同版本号的应用程序重复安装。在安装之前,请先卸载当前版本.再尝试安装。如果仍然失败.我推测可能是V1签名的问题(不能肯定),请等待新版本或者自行编译项目。
我现在是上学期间,使用kindle回复你的问题,暂时只能说这些了。

**Comment by lizeyan200711** [comment]
我的系统是Android6.0-emui4.0，我试过删除，重复安装，但它还是一样

**Comment by longjunyu2** [comment]
v1签名问题

**Comment by by-scott** [comment]
> v1签名问题



> v1签名问题

我记得我用的v2
