### ISSUE TITLE
Audio won't work with forge

### ISSUE THREAD

**Issue by Jokkaj** [longjunyu2/MCinaBox#94]
It won't work with forge or optifine and also, it says "missing pack.mcmeta" in the resourcepack menu.
I tried the in-app forge installer and the old way of installing from the pc files, it just won't work

**Comment by longjunyu2** [comment]
This is caused by the missing of ```assetIndex``` and ```assets``` arguments in forge json which may occur on some versions of forge.
You can copy the missing arguments from ```origin version json``` and add them to ```forge json```. This will solve the problem temp.

**Comment by Jokkaj** [comment]
> 
> 
> This is caused by the missing of `assetIndex` and `assets` arguments in forge json which may occur on some versions of forge.
> You can copy the missing arguments from `origin version json` and add them to `forge json`. This will solve the problem temp.

Yeah this fixes the issue, here I have the .json files for the latest forge and optifine releases (they are from the versions folder) with assets fixed
[Fixed JSONs .zip](https://github.com/longjunyu2/MCinaBox/files/4499544/Fixed.JSONs.zip)
