### ISSUE TITLE
Allow SD card location to be configured

### ISSUE THREAD

**Issue by Johnanater** [longjunyu2/MCinaBox#95]
Some phones do not use the location /sdcard/ as a mount point for SD cards. It would be nice if this was configurable inside the app.

**Comment by longjunyu2** [comment]
Yes. Some Android use other location to mount SD card. MCinaBox will use Environment to get the correct location instead of /sdcard.

**Comment by vico93** [comment]
> Yes. Some Android use other location to mount SD card. MCinaBox will use Environment to get the correct location instead of /sdcard.

For me (Samsung Galaxy A8) it uses `/sdcard/´ as the internal storage, and for SD Card it uses `/storage/XXXX-XXXX` (the X are numbers).

So for me MCinabox are saving .minecraft folder on internal storage (where i have few space) and not in SD Card (where i have plenty of space).
