### ISSUE TITLE
Please complete launcher configuration

### ISSUE THREAD

**Issue by FranzelDamasco909** [longjunyu2/MCinaBox#97]
pls can someone tell me how to complete and start the game?

**Comment by FranzelDamasco909** [comment]
i already installed the game files and i don't know how to co.plete the launcher configuration

**Comment by LegacyGamerHD** [comment]
if dont know how then just dont use then

**Comment by LegacyGamerHD** [comment]
literly its easy to todo

**Comment by FranzelDamasco909** [comment]
please tell me

**Comment by FranzelDamasco909** [comment]
sorry for being stupid but i don't really know how

**Comment by longjunyu2** [comment]
yes,you will do it

**Comment by Doguinn** [comment]
> you will do it :)

What what help me
